return {
	[6000] = {
		action_suffix = "",
		title = "综合科办公室",
		desc = "深空之眼综合科的专用办公室，配备有高效便捷的常规事务处理系统。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 1,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "默认解锁",
		prefix = "",
		light_effect_delay = "",
		id = 6000,
		default_music = 4,
		impact = {
			3
		},
		scene_tag = {
			103
		},
		scene_setting = {
			3
		},
		obtain_way = {}
	},
	[6001] = {
		action_suffix = "",
		title = "暮色珍珠",
		desc = "塔列朗集团重金购入的高级商务游艇，后来划归深空之眼所有，常被用于商务洽谈。\n\n<color=#939393>提示：场景推荐音乐为Lullaby, for a stranded heart。\n管理员可以通过下方按钮选择是否切换为该曲目。</color>",
		obtain_word = "\t",
		scene_trial = 1,
		limit_display = 1,
		prefix_dlc = "",
		unlock_description = "参与「夜宴之邀」活动获取",
		prefix = "X201",
		id = 6001,
		default_music = 53,
		impact = {},
		scene_tag = {
			101,
			102,
			104
		},
		scene_setting = {
			1,
			3
		},
		obtain_way = {
			2901,
			272211
		},
		light_effect_delay = {
			{
				0,
				3,
				2.8
			},
			{
				3.9,
				0,
				0
			},
			{
				6.3,
				0,
				0
			}
		},
		light_effect = {
			"Effect/Scene/X201/fx_X201_scene_1",
			"Effect/Scene/X201/fx_X201_scene_2",
			"Effect/Scene/X201/fx_X201_scene_3"
		}
	},
	[6003] = {
		action_suffix = "",
		title = "特别看护",
		desc = "急救科普活动结束后，国常立单独将你留在了病房里。\n「这位同学似乎需要一对一的护理示范，需要姐姐来教教你吗？」",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X301",
		light_effect_delay = "",
		id = 6003,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {},
		obtain_way = {}
	},
	[6004] = {
		action_suffix = "",
		title = "朱阁幽话",
		desc = "探访古墓旧址归来，陵光希望你在房中多留一阵。\n——「这身衣服……也就穿来给你看看，今晚之后我便收进衣柜……不再碰它了。」",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X302",
		light_effect_delay = "",
		id = 6004,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {},
		obtain_way = {}
	},
	[6005] = {
		action_suffix = "",
		title = "相见欢",
		desc = "游玩尽兴归来，执明略有犹豫地将你带到水边，履行刚刚打赌输掉的承诺。\n——「别离我太远，也……也别太近！这样刚刚好……就好……」",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X303",
		light_effect_delay = "",
		id = 6005,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {
			1
		},
		obtain_way = {}
	},
	[6006] = {
		action_suffix = "",
		title = "青玉案",
		desc = "是凤箫宛转，是灯火阑珊，是满城喧嚣里独属于你的一份笑语嫣然。\n「只是被你拖着走太远累了而已。你到底在期待什么？」",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X304",
		light_effect_delay = "",
		id = 6006,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {},
		obtain_way = {}
	},
	[6007] = {
		action_suffix = "",
		title = "花庭余响",
		desc = "午后的阳光，微醺的风和让人沉醉的花香。这首琴曲是今天独属于你我的纪念——让人难以忘却的、令人心动的纪念。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X305",
		light_effect_delay = "",
		id = 6007,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {
			1
		},
		obtain_way = {}
	},
	[6008] = {
		action_suffix = "",
		title = "轻舞幽梦",
		desc = "只属于管理员的观舞时间。眼前人身姿绰约，气若幽兰，恍惚中已再难分辨，这静好时光，到底是真是梦？",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X307",
		light_effect_delay = "",
		id = 6008,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {},
		obtain_way = {}
	},
	[6009] = {
		action_suffix = "",
		title = "休憩时间",
		desc = "电梯间偶然的相遇，让人无意中看到了庚辰的另一面。或许加紧定制的衣服，总不那么如人意……？",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X306",
		light_effect_delay = "",
		id = 6009,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {},
		obtain_way = {}
	},
	[6010] = {
		action_suffix = "",
		title = "慌张时刻",
		desc = "平日里总是有条不紊的工作状态，不知为何在管理员来到身边后，就会变得失误连连。原来英招部长也会有如此慌张的一面？",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X306a",
		light_effect_delay = "",
		id = 6010,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {},
		obtain_way = {}
	},
	[6011] = {
		action_suffix = "",
		title = "梦游奇境",
		desc = "傍晚时分，管理员遇见了沉醉在甜梦中的少女，静谧的黄昏中，唯有时间静静流逝。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X308",
		light_effect_delay = "",
		id = 6011,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {
			1
		},
		obtain_way = {}
	},
	[6012] = {
		action_suffix = "",
		title = "浮光的初景",
		desc = "未曾见过的景色，陌生的海岸，一切都让少女有些无所适从，此时管理员采取的策略是……？",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X310",
		light_effect_delay = "",
		id = 6012,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {
			1
		},
		obtain_way = {}
	},
	[6013] = {
		action_suffix = "",
		title = "温柔的回响",
		desc = "这份波塞冬一直珍视的景色只想与眼前的你分享。\n——让那个夏天成为最美好的回忆。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X311",
		light_effect_delay = "",
		id = 6013,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {
			1
		},
		obtain_way = {}
	},
	[6014] = {
		action_suffix = "",
		title = "于月色中",
		desc = "晚风吹过塞勒涅的发梢，这小小的天地虽静谧却充满着诗意。海浪温柔得像是天边莹莹月色，而月色像是她回首望向你的眼波。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X309",
		light_effect_delay = "",
		id = 6014,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {
			1
		},
		obtain_way = {}
	},
	[6015] = {
		action_suffix = "",
		title = "少女的绮想",
		desc = "为了等待归来的管理员，少女早早买好了饮料，但不知为何，只要和管理员待在一起，似乎步调总是会被打乱？",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X312",
		light_effect_delay = "",
		id = 6015,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {
			1
		},
		obtain_way = {}
	},
	[6016] = {
		action_suffix = "",
		title = "嬉闹午后",
		desc = "午后的房间里，梵天那一时兴起的言语究竟是真是假……？恐怕这个问题的答案，只有她自己知道。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X313",
		light_effect_delay = "",
		id = 6016,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {},
		obtain_way = {}
	},
	[6017] = {
		action_suffix = "day",
		title = "思念的归处·晨意",
		desc = "管理员名下的套房，位于启城某处高楼的顶层。疲惫时绝佳的、无人打扰的休憩之地。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 1,
		prefix_dlc = "X203",
		light_effect = "",
		unlock_description = "参与「观星手记」活动获取",
		prefix = "X203b",
		light_effect_delay = "",
		id = 6017,
		default_music = 274,
		impact = {},
		scene_tag = {
			105,
			107,
			108
		},
		scene_setting = {
			3
		},
		obtain_way = {
			2901,
			292211
		}
	},
	[6018] = {
		action_suffix = "night",
		title = "思念的归处·夜语",
		desc = "与托特相约观测星云之后的安睡之处，沉沉的夜色总有绚烂的星云相伴。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 1,
		prefix_dlc = "X203a",
		light_effect = "",
		unlock_description = "参与「观星手记」活动获取",
		prefix = "X203c",
		light_effect_delay = "",
		id = 6018,
		default_music = 275,
		impact = {},
		scene_tag = {
			106,
			107,
			108,
			104
		},
		scene_setting = {
			1,
			3
		},
		obtain_way = {
			2901,
			292211
		}
	},
	[6021] = {
		action_suffix = "",
		title = "倦梦夜华",
		desc = "喧嚣的晚宴结束后，二人在车上品味着今夜的余韵，对帕尔瓦蒂来说，这才是真正能够放松的时刻。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X316",
		light_effect_delay = "",
		id = 6021,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {
			1
		},
		obtain_way = {}
	},
	[6022] = {
		action_suffix = "",
		title = "纯白之誓",
		desc = "无论艰难与困苦、逆境与挑战，无论相隔的距离久远，别离的时间悠长，我也总会因你，眼中泛起涟漪。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X317",
		light_effect_delay = "",
		id = 6022,
		default_music = 146,
		impact = {},
		scene_tag = {},
		scene_setting = {
			1,
			3
		},
		obtain_way = {}
	},
	[6023] = {
		action_suffix = "",
		title = "诚挚心意",
		desc = "专属女仆站在你的面前，她所有的目光都凝聚于你，她所有的想法都为你而动。吃下这道魔法蛋包饭，记得回应她小心而又诚挚的心意。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X318",
		light_effect_delay = "",
		id = 6023,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {
			1
		},
		obtain_way = {}
	},
	[6024] = {
		action_suffix = "",
		title = "烘焙甜蜜",
		desc = "假装一切都是再普通不过的日常，假装蛋糕中并没有藏入多余的心意，假装从未偷偷注意你。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X319",
		light_effect_delay = "",
		id = 6024,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {
			1
		},
		obtain_way = {}
	},
	[6025] = {
		action_suffix = "",
		title = "星灯下的梦",
		desc = "松针在风中轻颤，烂漫的光点染一片漆黑的夜晚。海姆达尔安静坐在树下，期待你记住这个属于你们的梦。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X320",
		light_effect_delay = "",
		id = 6025,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {
			1
		},
		obtain_way = {}
	},
	[6026] = {
		action_suffix = "",
		title = "知我意",
		desc = "少女带着最纯粹的愿景送出了对你的祝福，或许她已暴露出自己都未发觉到的情愫。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X321",
		light_effect_delay = "",
		id = 6026,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {
			1
		},
		obtain_way = {}
	},
	[6027] = {
		action_suffix = "",
		title = "预设中的意外",
		desc = "恰到好处的动作，精心设计的言语，少女脸上隐约可见的红晕，暴露出想与你拉进距离的心绪。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X323",
		light_effect_delay = "",
		id = 6027,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {
			1
		},
		obtain_way = {}
	},
	[6028] = {
		action_suffix = "",
		title = "杯光摇曳时",
		desc = "斑驳的灯光在杯中摇曳，映衬着塞勒涅泛波的眼眸。今夜情思如月浸入杯中，惟愿你我此刻永恒。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X324",
		light_effect_delay = "",
		id = 6028,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {
			1
		},
		obtain_way = {}
	},
	[6029] = {
		action_suffix = "",
		title = "指名服务",
		desc = "或许其实只是想见你，所以才知道你会出现在这里，等待着你被她「指名」。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X322",
		light_effect_delay = "",
		id = 6029,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {
			1
		},
		obtain_way = {}
	},
	[6031] = {
		action_suffix = "",
		title = "不思量",
		desc = "阶前细雨，廊边红袖，透过半掩的扇子，从她流转的眸光中，你似乎看见了自己的倒影。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 0,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "",
		prefix = "X325",
		light_effect_delay = "",
		id = 6031,
		default_music = 0,
		impact = {},
		scene_tag = {},
		scene_setting = {
			1
		},
		obtain_way = {}
	},
	[6100] = {
		action_suffix = "",
		title = "作战中心大厅",
		desc = "深空之眼作战中心大厅，是第九部门进行作战情报分析演算的场所，管理员通常在这里完成行动前战略规划。",
		obtain_word = "",
		scene_trial = 0,
		limit_display = 1,
		prefix_dlc = "",
		light_effect = "",
		unlock_description = "默认解锁",
		prefix = "X202",
		light_effect_delay = "",
		id = 6100,
		default_music = 201,
		impact = {},
		scene_tag = {},
		scene_setting = {
			3
		},
		obtain_way = {}
	},
	all = {
		6000,
		6001,
		6003,
		6004,
		6005,
		6006,
		6007,
		6008,
		6009,
		6010,
		6011,
		6012,
		6013,
		6014,
		6015,
		6016,
		6017,
		6018,
		6021,
		6022,
		6023,
		6024,
		6025,
		6026,
		6027,
		6028,
		6029,
		6031,
		6100
	}
}
