return {
	CD_KEY = 1,
	ACTIVITY = 13,
	SHOP_TAOBAO = 14,
	OFFICIAL_WEBSITE = 4,
	ATTENTION = 3,
	QUESTIONNAIRE = 2,
	MANUAL_WORD_VERIFY = 16,
	TRANSFER_CODE = 17,
	SUGGEST = 6,
	CHANGE_NICK = 9,
	INQUERY = 8,
	USER_CENTER = 5,
	SHARE_FLAG = 11,
	FORUM = 7,
	CHANGE_SIGN = 10,
	INFOMATION = 15,
	PLATFORM = {
		BILIBILI = 3,
		WEIBO = 1,
		WECHAT = 2,
		FACEBOOK = 5,
		DISCORD = 6,
		YOUTUBE = 7,
		TWITTER = 4
	},
	SURVEY_TYPE = {
		NORMAL = 1,
		REGRESSION = 2
	},
	OPERATION_STOP = {
		JOIN_CLUB = 201,
		CHANGE_CLUB_SIGN = 203,
		PASSPORT_BUY = 9011,
		DAMAGE_TEST = 902,
		CHANGE_CLUB_NICK = 202
	},
	URL_OPEN_WAY = {
		NORMAL = 1,
		INTERNAL = 2
	},
	SCREEN_ORIENTATION = {
		FORCE_HORIZONTAL = 0,
		FORCE_VERTICAL = 1,
		FREE = -1
	}
}
