return {
	{
		cueName = "bgm_promotion_1_0_promise_long",
		authorName = "祈Inory",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_promotion_1_0_promise_long",
		musicName = "Promise",
		id = 1,
		awbName = "bgm_promotion_1_0_promise_long",
		initAISAC = "",
		detail = "曲名：Promise\n演唱：祈Inory\n作曲：Polymath9\n编曲：Polymath9×S9ryne\n作词：TetraCalyx\n吉他：绛舞乱丸\n混音：Mr_LTC\n母带：火花声影文化工作室\n制作：Polymath9"
	},
	{
		cueName = "bgm_promotion_1_0_promise_short",
		authorName = "祈Inory",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_promotion_1_0_promise_short",
		musicName = "Promise (Short Ver.)",
		id = 2,
		awbName = "bgm_promotion_1_0_promise_short",
		initAISAC = "",
		detail = "曲名：Promise (Short Ver.)\n演唱：祈Inory\n作曲：Polymath9\n编曲：Polymath9×S9ryne\n作词：TetraCalyx\n吉他：绛舞乱丸\n混音：Mr_LTC\n母带：火花声影文化工作室\n制作：Polymath9"
	},
	{
		cueName = "bgm_login",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_login",
		musicName = "Intro",
		id = 3,
		awbName = "bgm_login",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_main_01",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_main_01",
		musicName = "Lobby",
		id = 4,
		awbName = "bgm_main_01",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_battle_choose_01",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_battle_choose_01",
		musicName = "Make a Choice",
		id = 5,
		awbName = "bgm_battle_choose_01",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_theme_muluoniya_01",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_theme_muluoniya_01",
		musicName = "Neuhansa",
		id = 6,
		awbName = "bgm_theme_muluoniya_01",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_normal_battle",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_normal_battle",
		musicName = "Go Ahead",
		id = 7,
		awbName = "bgm_normal_battle",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_boss_theme_phase",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_boss_theme_phase",
		musicName = "Block Off (Phase 1)",
		id = 8,
		awbName = "bgm_boss_theme_phase",
		detail = "作曲：CoyDe",
		initAISAC = {
			{
				"bgm_volume",
				0
			}
		}
	},
	{
		cueName = "bgm_boss_theme_phase",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_boss_theme_phase",
		musicName = "Block Off (Phase 2)",
		id = 9,
		awbName = "bgm_boss_theme_phase",
		detail = "作曲：CoyDe",
		initAISAC = {
			{
				"bgm_volume",
				1
			}
		}
	},
	{
		cueName = "bgm_boss_battle_01",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_boss_battle_01",
		musicName = "Bifrons",
		id = 10,
		awbName = "bgm_boss_battle_01",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_battle_sipierte_01",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_battle_sipierte_01",
		musicName = "Spealght",
		id = 11,
		awbName = "bgm_battle_sipierte_01",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_battle_xinmo",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_battle_xinmo",
		musicName = "Fight For Me",
		id = 12,
		awbName = "bgm_battle_xinmo",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_boss_battle_02",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_boss_battle_02",
		musicName = "Halphas (Phase 1)",
		id = 13,
		awbName = "bgm_boss_battle_02",
		detail = "作曲：CoyDe",
		initAISAC = {
			{
				"bgm_volume",
				0
			}
		}
	},
	{
		cueName = "bgm_boss_battle_02",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_boss_battle_02",
		musicName = "Halphas (Phase 2)",
		id = 14,
		awbName = "bgm_boss_battle_02",
		detail = "模仿了这么多年人工智能讲话，确实让我有点模糊了……\n你们，应该为自己能成为那位大人霸业的垫脚石而感到荣幸！\n\n作曲：CoyDe",
		initAISAC = {
			{
				"bgm_volume",
				1
			}
		}
	},
	{
		cueName = "bgm_warchess_01_factory",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_warchess_01_factory",
		musicName = "Searching",
		id = 15,
		awbName = "bgm_warchess_01_factory",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_count",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_victory_count",
		musicName = "Victory",
		id = 16,
		awbName = "bgm_victory_count",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_theme_yujing_01",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_theme_yujing_01",
		musicName = "Sasanami Theme",
		id = 17,
		awbName = "bgm_theme_yujing_01",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_battle_yujing_01",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_battle_yujing_01",
		musicName = "Fighting in Sasanami 1",
		id = 18,
		awbName = "bgm_battle_yujing_01",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_battle_yujing_02",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_battle_yujing_02",
		musicName = "Fighting in Sasanami 2",
		id = 19,
		awbName = "bgm_battle_yujing_02",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_boss_battle_03",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_boss_battle_03",
		musicName = "Orochi (Phase 1)",
		id = 20,
		awbName = "bgm_boss_battle_03",
		detail = "作曲：CoyDe",
		initAISAC = {
			{
				"bgm_volume",
				0
			}
		}
	},
	{
		cueName = "bgm_boss_battle_03",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_boss_battle_03",
		musicName = "Orochi (Phase 2)",
		id = 21,
		awbName = "bgm_boss_battle_03",
		detail = "我曾被人人尊为神祇，亦遭人人惧之如凶灾。\n凡人皆畏我、敬我、惧我、拜我——\n须臾百年，就叫你们就忘了这片土地原本的主人是谁吗？\n\n作曲：CoyDe",
		initAISAC = {
			{
				"bgm_volume",
				1
			}
		}
	},
	{
		cueName = "bgm_story_v0_prologue",
		authorName = "M€I",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_story_v0_prologue",
		musicName = "Gaea",
		id = 22,
		awbName = "bgm_story_v0_prologue",
		initAISAC = "",
		detail = "作曲：M€I"
	},
	{
		cueName = "bgm_story_v0_battleground",
		authorName = "M€I",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_story_v0_battleground",
		musicName = "Digofaint Gaea",
		id = 23,
		awbName = "bgm_story_v0_battleground",
		initAISAC = "",
		detail = "作曲：M€I"
	},
	{
		cueName = "bgm_story_v1_battleground_1",
		authorName = "M€I",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_story_v1_battleground_1",
		musicName = "Ffatri Wail",
		id = 24,
		awbName = "bgm_story_v1_battleground_1",
		initAISAC = "",
		detail = "作曲：M€I"
	},
	{
		cueName = "bgm_story_v1_battleground_2",
		authorName = "M€I",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_story_v1_battleground_2",
		musicName = "Crisis coming",
		id = 25,
		awbName = "bgm_story_v1_battleground_2",
		initAISAC = "",
		detail = "作曲：M€I"
	},
	{
		cueName = "bgm_story_scheme",
		authorName = "M€I",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_story_scheme",
		musicName = "Cynllun",
		id = 26,
		awbName = "bgm_story_scheme",
		initAISAC = "",
		detail = "作曲：M€I"
	},
	{
		cueName = "bgm_story_v1_qiaolin",
		authorName = "M€I",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_story_v1_qiaolin",
		musicName = "The old man",
		id = 27,
		awbName = "bgm_story_v1_qiaolin",
		initAISAC = "",
		detail = "未能守护的心血和无法写就的十四行诗。\n\n作曲：M€I"
	},
	{
		cueName = "bgm_story_office",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_story_office",
		musicName = "Office",
		id = 28,
		awbName = "bgm_story_office",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_story_mood_daily",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_story_mood_daily",
		musicName = "Daily",
		id = 29,
		awbName = "bgm_story_mood_daily",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_story_mood_warm",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_story_mood_warm",
		musicName = "Warmth",
		id = 30,
		awbName = "bgm_story_mood_warm",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_0_1_osiris_ui",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 2,
		cuesheet = "bgm_activity_1_0_1_osiris_ui",
		musicName = "Osiris",
		id = 31,
		awbName = "bgm_activity_1_0_1_osiris_ui",
		initAISAC = "",
		detail = "那曾经高悬头顶的红蔷薇。\n坠于大地，徒留怨恨，流淌至今。\n\n作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_1_hel_ui",
		authorName = "CoyDe feat. Polymath9",
		ableBGM = 1,
		album = 3,
		cuesheet = "bgm_activity_1_1_hel_ui",
		musicName = "Dancing With Helena",
		id = 32,
		awbName = "bgm_activity_1_1_hel_ui",
		initAISAC = "",
		detail = "再见，再见，我亲爱的海伦娜。\n\n作曲：CoyDe feat. Polymath9\n编曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_1_hel_story_warm",
		authorName = "M€I",
		ableBGM = 1,
		album = 3,
		cuesheet = "bgm_activity_1_1_hel_story_warm",
		musicName = "Your Love",
		id = 33,
		awbName = "bgm_activity_1_1_hel_story_warm",
		initAISAC = "",
		detail = "作曲：M€I"
	},
	{
		cueName = "bgm_activity_1_1_hel_story",
		authorName = "M€I",
		ableBGM = 1,
		album = 3,
		cuesheet = "bgm_activity_1_1_hel_story",
		musicName = "Lucid Dreams",
		id = 34,
		awbName = "bgm_activity_1_1_hel_story",
		initAISAC = "",
		detail = "作曲：M€I"
	},
	{
		cueName = "bgm_activity_1_1_hel_warchess",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 3,
		cuesheet = "bgm_activity_1_1_hel_warchess",
		musicName = "Lose Yourself",
		id = 35,
		awbName = "bgm_activity_1_1_hel_warchess",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_1_hel_battle_city",
		authorName = "Moto",
		ableBGM = 1,
		album = 3,
		cuesheet = "bgm_activity_1_1_hel_battle_city",
		musicName = "Where",
		id = 36,
		awbName = "bgm_activity_1_1_hel_battle_city",
		initAISAC = "",
		detail = "作曲：Moto"
	},
	{
		cueName = "bgm_activity_1_1_hel_battle_graveyard",
		authorName = "Moto",
		ableBGM = 1,
		album = 3,
		cuesheet = "bgm_activity_1_1_hel_battle_graveyard",
		musicName = "Did You",
		id = 37,
		awbName = "bgm_activity_1_1_hel_battle_graveyard",
		initAISAC = "",
		detail = "作曲：Moto"
	},
	{
		cueName = "bgm_activity_1_1_hel_battle_lab",
		authorName = "Moto",
		ableBGM = 1,
		album = 3,
		cuesheet = "bgm_activity_1_1_hel_battle_lab",
		musicName = "Red Light (From WDYG)",
		id = 38,
		awbName = "bgm_activity_1_1_hel_battle_lab",
		initAISAC = "",
		detail = "作曲：Moto"
	},
	{
		cueName = "bgm_activity_1_1_1_hermes_parkour",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 3,
		cuesheet = "bgm_activity_1_1_1_hermes_parkour",
		musicName = "GOGOGO!Hermes!",
		id = 39,
		awbName = "bgm_activity_1_1_1_hermes_parkour",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_1_1_hermes_story",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 3,
		cuesheet = "bgm_activity_1_1_1_hermes_story",
		musicName = "Hermes",
		id = 40,
		awbName = "bgm_activity_1_1_1_hermes_story",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_warchess_02_sasanami",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 3,
		cuesheet = "bgm_warchess_02_sasanami",
		musicName = "Salvatio",
		id = 41,
		awbName = "bgm_warchess_02_sasanami",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_2_summer1_ui",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 4,
		cuesheet = "bgm_activity_1_2_summer1_ui",
		musicName = "Summer Holiday",
		id = 42,
		awbName = "bgm_activity_1_2_summer1_ui",
		initAISAC = "",
		detail = "曾见过遥远宁静的边界，也战胜过汹涌险恶的风暴，这就是我与雪晶二号的羁绊和奇迹！\n\n作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_2_summer1_battle_beach",
		authorName = "M€I",
		ableBGM = 1,
		album = 4,
		cuesheet = "bgm_activity_1_2_summer1_battle_beach",
		musicName = "Beach Party",
		id = 43,
		awbName = "bgm_activity_1_2_summer1_battle_beach",
		initAISAC = "",
		detail = "作曲：M€I"
	},
	{
		cueName = "bgm_activity_1_2_summer1_battle_jungle",
		authorName = "M€I",
		ableBGM = 1,
		album = 4,
		cuesheet = "bgm_activity_1_2_summer1_battle_jungle",
		musicName = "Chasing",
		id = 44,
		awbName = "bgm_activity_1_2_summer1_battle_jungle",
		initAISAC = "",
		detail = "作曲：M€I"
	},
	{
		cueName = "bgm_activity_1_2_summer1_battle_deck",
		authorName = "M€I",
		ableBGM = 1,
		album = 4,
		cuesheet = "bgm_activity_1_2_summer1_battle_deck",
		musicName = "Violent Movement",
		id = 45,
		awbName = "bgm_activity_1_2_summer1_battle_deck",
		initAISAC = "",
		detail = "作曲：M€I"
	},
	{
		cueName = "bgm_activity_1_2_1_summer2_story_boss1",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 4,
		cuesheet = "bgm_activity_1_2_1_summer2_story_boss1",
		musicName = "Siren Silence",
		id = 46,
		awbName = "bgm_activity_1_2_1_summer2_story_boss1",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_2_1_summer2_story_boss2",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 4,
		cuesheet = "bgm_activity_1_2_1_summer2_story_boss2",
		musicName = "Siren Silence Plus",
		id = 47,
		awbName = "bgm_activity_1_2_1_summer2_story_boss2",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_2_1_summer2_battle",
		authorName = "Polymath9/雷声",
		ableBGM = 1,
		album = 4,
		cuesheet = "bgm_activity_1_2_1_summer2_battle",
		musicName = "Siren: Remotum Punctum",
		id = 48,
		awbName = "bgm_activity_1_2_1_summer2_battle",
		initAISAC = "",
		detail = "你们拒绝……梦……\n……现实……就是真的吗……？\n\n曲名：Siren: Remotum Punctum\n作曲：Polymath9\n编曲：雷声/Polymath9"
	},
	{
		cueName = "bgm_activity_1_2_summer1_minigame_racing",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 4,
		cuesheet = "bgm_activity_1_2_summer1_minigame_racing",
		musicName = "Game Start",
		id = 49,
		awbName = "bgm_activity_1_2_summer1_minigame_racing",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_2_summer1_minigame_fishing",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 4,
		cuesheet = "bgm_activity_1_2_summer1_minigame_fishing",
		musicName = "Taste",
		id = 50,
		awbName = "bgm_activity_1_2_summer1_minigame_fishing",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_2_summer1_story_relax",
		authorName = "Moto",
		ableBGM = 1,
		album = 4,
		cuesheet = "bgm_activity_1_2_summer1_story_relax",
		musicName = "Dream For You",
		id = 51,
		awbName = "bgm_activity_1_2_summer1_story_relax",
		initAISAC = "",
		detail = "作曲：Moto"
	},
	{
		cueName = "bgm_activity_1_2_summer1_story_intense",
		authorName = "Moto",
		ableBGM = 1,
		album = 4,
		cuesheet = "bgm_activity_1_2_summer1_story_intense",
		musicName = "Ambush",
		id = 52,
		awbName = "bgm_activity_1_2_summer1_story_intense",
		initAISAC = "",
		detail = "作曲：Moto"
	},
	{
		cueName = "bgm_activity_1_2_summer1_story_beach",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 4,
		cuesheet = "bgm_activity_1_2_summer1_story_beach",
		musicName = "Lullaby, for a stranded heart",
		id = 53,
		awbName = "bgm_activity_1_2_summer1_story_beach",
		initAISAC = "",
		detail = "跳动的篝火，勾勒出船长和水手的形貌。\n\n曲名：Lullaby, for a stranded heart\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_1_2_summer1_story_ghost",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 4,
		cuesheet = "bgm_activity_1_2_summer1_story_ghost",
		musicName = "Get spooked!! Wait…",
		id = 54,
		awbName = "bgm_activity_1_2_summer1_story_ghost",
		initAISAC = "",
		detail = "作曲：Polymath9\n混音：雷声"
	},
	{
		cueName = "bgm_activity_1_2_1_summer2_story_general",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 4,
		cuesheet = "bgm_activity_1_2_1_summer2_story_general",
		musicName = "Aspire",
		id = 55,
		awbName = "bgm_activity_1_2_1_summer2_story_general",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_2_1_summer2_story_2_1",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 4,
		cuesheet = "bgm_activity_1_2_1_summer2_story_2_1",
		musicName = "Break through, and dive deeper (Part 1)",
		id = 56,
		awbName = "bgm_activity_1_2_1_summer2_story_2_1",
		detail = "曲名：Break through, and dive deeper (Part 1)\n作曲：Polymath9\n编曲：Polymath9/雷声\n混音：雷声",
		initAISAC = {
			{
				"phase_controller",
				0.6
			}
		}
	},
	{
		cueName = "bgm_activity_1_2_1_summer2_story_2_1_wave",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 4,
		cuesheet = "bgm_activity_1_2_1_summer2_story_2_1_wave",
		musicName = "Break through, and dive deeper (Part 2)",
		id = 57,
		awbName = "bgm_activity_1_2_1_summer2_story_2_1_wave",
		initAISAC = "",
		detail = "曲名：Break through, and dive deeper (Part 2)\n作曲：Polymath9\n混音：雷声"
	},
	{
		cueName = "bgm_activity_1_3_ui",
		authorName = "Tony",
		ableBGM = 1,
		album = 5,
		cuesheet = "bgm_activity_1_3_ui",
		musicName = "Arena",
		id = 58,
		awbName = "bgm_activity_1_3_ui",
		initAISAC = "",
		detail = "万众瞩目之下，一场即将开幕的盛典——\n\n作曲：Tony"
	},
	{
		cueName = "bgm_activity_1_3_battle1",
		authorName = "Tony",
		ableBGM = 1,
		album = 5,
		cuesheet = "bgm_activity_1_3_battle1",
		musicName = "Gladiatorial Drumming",
		id = 59,
		awbName = "bgm_activity_1_3_battle1",
		initAISAC = "",
		detail = "作曲：Tony"
	},
	{
		cueName = "bgm_activity_1_3_boss_4023",
		authorName = "Tony",
		ableBGM = 1,
		album = 5,
		cuesheet = "bgm_activity_1_3_boss_4023",
		musicName = "Athena Sonatina",
		id = 60,
		awbName = "bgm_activity_1_3_boss_4023",
		initAISAC = "",
		detail = "只要这片土地上还有追求自由和创造的人们，铃兰团就有为之而战的意义。\n\n作曲：Tony"
	},
	{
		cueName = "bgm_activity_1_3_warchess",
		authorName = "Tony",
		ableBGM = 1,
		album = 5,
		cuesheet = "bgm_activity_1_3_warchess",
		musicName = "Checkerboard Chaconne",
		id = 61,
		awbName = "bgm_activity_1_3_warchess",
		initAISAC = "",
		detail = "作曲：Tony"
	},
	{
		cueName = "bgm_activity_1_3_story_indoor",
		authorName = "Tony",
		ableBGM = 1,
		album = 5,
		cuesheet = "bgm_activity_1_3_story_indoor",
		musicName = "Minuet of Art",
		id = 62,
		awbName = "bgm_activity_1_3_story_indoor",
		initAISAC = "",
		detail = "作曲：Tony"
	},
	{
		cueName = "bgm_activity_1_3_story_outdoor",
		authorName = "Tony",
		ableBGM = 1,
		album = 5,
		cuesheet = "bgm_activity_1_3_story_outdoor",
		musicName = "Gigue on the Street",
		id = 63,
		awbName = "bgm_activity_1_3_story_outdoor",
		initAISAC = "",
		detail = "作曲：Tony"
	},
	{
		cueName = "bgm_activity_1_3_story_battle",
		authorName = "Tony",
		ableBGM = 1,
		album = 5,
		cuesheet = "bgm_activity_1_3_story_battle",
		musicName = "Combat Prelude",
		id = 64,
		awbName = "bgm_activity_1_3_story_battle",
		initAISAC = "",
		detail = "作曲：Tony"
	},
	{
		cueName = "bgm_activity_1_3_story_destroyed",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 5,
		cuesheet = "bgm_activity_1_3_story_destroyed",
		musicName = "Ars Fracta",
		id = 65,
		awbName = "bgm_activity_1_3_story_destroyed",
		initAISAC = "",
		detail = "作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_1_3_1_minigame_open",
		authorName = "雷声",
		ableBGM = 1,
		album = 5,
		cuesheet = "bgm_activity_1_3_1_minigame_open",
		musicName = "Zenkibo no Itazura",
		id = 66,
		awbName = "bgm_activity_1_3_1_minigame_open",
		initAISAC = "",
		detail = "作曲：雷声"
	},
	{
		cueName = "bgm_activity_1_3_1_minigame_main",
		authorName = "雷声",
		ableBGM = 1,
		album = 5,
		cuesheet = "bgm_activity_1_3_1_minigame_main",
		musicName = "Zenkibo no Haisou",
		id = 67,
		awbName = "bgm_activity_1_3_1_minigame_main",
		initAISAC = "",
		detail = "作曲：雷声"
	},
	{
		cueName = "bgm_activity_1_4_ui",
		authorName = "Tony",
		ableBGM = 1,
		album = 6,
		cuesheet = "bgm_activity_1_4_ui",
		musicName = "Theatre Flame",
		id = 68,
		awbName = "bgm_activity_1_4_ui",
		initAISAC = "",
		detail = "中止的盛典，反而带来新生的序曲。\n\n作曲：Tony"
	},
	{
		cueName = "bgm_activity_1_4_battle_source2",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 6,
		cuesheet = "bgm_activity_1_4_battle_source2",
		musicName = "Origin1",
		id = 69,
		awbName = "bgm_activity_1_4_battle_source2",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_4_battle_source1",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 6,
		cuesheet = "bgm_activity_1_4_battle_source1",
		musicName = "Origin2",
		id = 70,
		awbName = "bgm_activity_1_4_battle_source1",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_4_boss_4025_1",
		authorName = "Tony",
		ableBGM = 1,
		album = 6,
		cuesheet = "bgm_activity_1_4_boss_4025_1",
		musicName = "Artistic Danger",
		id = 71,
		awbName = "bgm_activity_1_4_boss_4025_1",
		initAISAC = "",
		detail = "作曲：Tony"
	},
	{
		cueName = "bgm_activity_1_4_boss_4025_2",
		authorName = "Tony",
		ableBGM = 1,
		album = 6,
		cuesheet = "bgm_activity_1_4_boss_4025_2",
		musicName = "Monster Within",
		id = 72,
		awbName = "bgm_activity_1_4_boss_4025_2",
		initAISAC = "",
		detail = "你们真的惹恼了拉冬大人…………\n嗯嗯，想让我手下留情？我偏不，那样可就不好玩了~\n\n作曲：Tony"
	},
	{
		cueName = "bgm_activity_1_4_story_source",
		authorName = "Tony",
		ableBGM = 1,
		album = 6,
		cuesheet = "bgm_activity_1_4_story_source",
		musicName = "Concert in the Dark",
		id = 73,
		awbName = "bgm_activity_1_4_story_source",
		initAISAC = "",
		detail = "作曲：Tony"
	},
	{
		cueName = "bgm_activity_1_4_story_surface",
		authorName = "Tony",
		ableBGM = 1,
		album = 6,
		cuesheet = "bgm_activity_1_4_story_surface",
		musicName = "Hidden Conflict",
		id = 74,
		awbName = "bgm_activity_1_4_story_surface",
		initAISAC = "",
		detail = "作曲：Tony"
	},
	{
		cueName = "bgm_side_daily01",
		authorName = "雷声",
		ableBGM = 1,
		album = 6,
		cuesheet = "bgm_side_daily01",
		musicName = "Futuristic Sights",
		id = 75,
		awbName = "bgm_side_daily01",
		initAISAC = "",
		detail = "作曲：雷声"
	},
	{
		cueName = "bgm_side_daily02",
		authorName = "雷声",
		ableBGM = 1,
		album = 6,
		cuesheet = "bgm_side_daily02",
		musicName = "Moment of Relaxation",
		id = 76,
		awbName = "bgm_side_daily02",
		initAISAC = "",
		detail = "作曲：雷声"
	},
	{
		cueName = "bgm_side_daily03",
		authorName = "雷声",
		ableBGM = 1,
		album = 6,
		cuesheet = "bgm_side_daily03",
		musicName = "Digital Heartbeats",
		id = 77,
		awbName = "bgm_side_daily03",
		initAISAC = "",
		detail = "作曲：雷声/Polymath9\n编曲：雷声"
	},
	{
		cueName = "bgm_side_daily04",
		authorName = "雷声",
		ableBGM = 1,
		album = 6,
		cuesheet = "bgm_side_daily04",
		musicName = "Perceived Crisis",
		id = 78,
		awbName = "bgm_side_daily04",
		initAISAC = "",
		detail = "作曲：雷声"
	},
	{
		cueName = "bgm_side_daily05",
		authorName = "雷声",
		ableBGM = 1,
		album = 6,
		cuesheet = "bgm_side_daily05",
		musicName = "Simulated Daylight",
		id = 79,
		awbName = "bgm_side_daily05",
		initAISAC = "",
		detail = "作曲：雷声"
	},
	{
		cueName = "bgm_side_daily06",
		authorName = "雷声",
		ableBGM = 1,
		album = 6,
		cuesheet = "bgm_side_daily06",
		musicName = "Information Intermission",
		id = 80,
		awbName = "bgm_side_daily06",
		initAISAC = "",
		detail = "作曲：雷声"
	},
	{
		cueName = "bgm_activity_1_5_login",
		authorName = "直惘",
		ableBGM = 1,
		album = 7,
		cuesheet = "bgm_activity_1_5_login",
		musicName = "Lost in waves",
		id = 81,
		awbName = "bgm_activity_1_5_login",
		initAISAC = "",
		detail = "黄沙，钢铁，雪茄。一场父与子之间的铜之决。\n\n作曲：雷声\n吉他：张宇煊"
	},
	{
		cueName = "bgm_activity_1_5_battle_1",
		authorName = "直惘",
		ableBGM = 1,
		album = 7,
		cuesheet = "bgm_activity_1_5_battle_1",
		musicName = "Warning!Warning!",
		id = 82,
		awbName = "bgm_activity_1_5_battle_1",
		initAISAC = "",
		detail = "作曲：雷声\n吉他：张宇煊"
	},
	{
		cueName = "bgm_activity_1_5_battle_2",
		authorName = "直惘",
		ableBGM = 1,
		album = 7,
		cuesheet = "bgm_activity_1_5_battle_2",
		musicName = "Modern shuffle slayer",
		id = 83,
		awbName = "bgm_activity_1_5_battle_2",
		initAISAC = "",
		detail = "作曲：雷声\n吉他：张宇煊"
	},
	{
		cueName = "bgm_activity_1_5_boss_4029",
		authorName = "直惘",
		ableBGM = 1,
		album = 7,
		cuesheet = "bgm_activity_1_5_boss_4029",
		musicName = "S.L.A.Y",
		id = 84,
		awbName = "bgm_activity_1_5_boss_4029",
		initAISAC = "",
		detail = "借来的秘密武器，潜伏的定时炸弹。\n\n作曲：雷声\n吉他：张宇煊"
	},
	{
		cueName = "bgm_activity_1_5_story_1",
		authorName = "雷声",
		ableBGM = 1,
		album = 7,
		cuesheet = "bgm_activity_1_5_story_1",
		musicName = "9et 0ut of neuro",
		id = 85,
		awbName = "bgm_activity_1_5_story_1",
		initAISAC = "",
		detail = "作曲：雷声"
	},
	{
		cueName = "bgm_activity_1_5_story_2",
		authorName = "雷声",
		ableBGM = 1,
		album = 7,
		cuesheet = "bgm_activity_1_5_story_2",
		musicName = "Nomorecrash",
		id = 86,
		awbName = "bgm_activity_1_5_story_2",
		initAISAC = "",
		detail = "作曲：雷声"
	},
	{
		cueName = "bgm_activity_1_5_story_3",
		authorName = "雷声",
		ableBGM = 1,
		album = 7,
		cuesheet = "bgm_activity_1_5_story_3",
		musicName = "Heavy-Neuro-Pr0gram",
		id = 87,
		awbName = "bgm_activity_1_5_story_3",
		initAISAC = "",
		detail = "作曲：雷声"
	},
	{
		cueName = "bgm_activity_1_6_ui",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 8,
		cuesheet = "bgm_activity_1_6_ui",
		musicName = "Avant un rêve",
		id = 88,
		awbName = "bgm_activity_1_6_ui",
		initAISAC = "",
		detail = "我仍然与小昙相遇。\n在千百个梦中。\n\n作曲：Polymath9\n鼓、混音：雷声"
	},
	{
		cueName = "bgm_activity_1_6_battle_skzy",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 8,
		cuesheet = "bgm_activity_1_6_battle_skzy",
		musicName = "Headquarters",
		id = 89,
		awbName = "bgm_activity_1_6_battle_skzy",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_6_battle_park_plaza",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 8,
		cuesheet = "bgm_activity_1_6_battle_park_plaza",
		musicName = "Valleyrand Park",
		id = 90,
		awbName = "bgm_activity_1_6_battle_park_plaza",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_6_battle_corg",
		authorName = "Haloweak",
		ableBGM = 1,
		album = 8,
		cuesheet = "bgm_activity_1_6_battle_corg",
		musicName = "The Supreme Scheme",
		id = 91,
		awbName = "bgm_activity_1_6_battle_corg",
		initAISAC = "",
		detail = "作曲：Haloweak"
	},
	{
		cueName = "bgm_activity_1_6_boss_4031_1",
		authorName = "Haloweak",
		ableBGM = 1,
		album = 8,
		cuesheet = "bgm_activity_1_6_boss_4031_1",
		musicName = "Dans mille rêves",
		id = 92,
		awbName = "bgm_activity_1_6_boss_4031_1",
		initAISAC = "",
		detail = "神之所以不亲自动手，那是因为对这世间仍抱有仁慈。\n倘若你们因此误会了神不具备征伐之能，那实在是愚昧得令我心痛了……\n\n作曲：Haloweak"
	},
	{
		cueName = "bgm_activity_1_6_boss_4031_2",
		authorName = "Haloweak",
		ableBGM = 1,
		album = 8,
		cuesheet = "bgm_activity_1_6_boss_4031_2",
		musicName = "Après mille rêves",
		id = 93,
		awbName = "bgm_activity_1_6_boss_4031_2",
		initAISAC = "",
		detail = "白与金交织连缀——洁白的武神张开她的羽翼。\n\n作曲：Haloweak\n编曲：Haloweak/Moto"
	},
	{
		cueName = "bgm_activity_1_6_story_skuld",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 8,
		cuesheet = "bgm_activity_1_6_story_skuld",
		musicName = "Rêves de retrouvailles",
		id = 94,
		awbName = "bgm_activity_1_6_story_skuld",
		initAISAC = "",
		detail = "高墙之外，人海之中。\n\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_1_6_story_story",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 8,
		cuesheet = "bgm_activity_1_6_story_story",
		musicName = "Rêves d'extérieur",
		id = 95,
		awbName = "bgm_activity_1_6_story_story",
		detail = "作曲：Polymath9",
		initAISAC = {
			{
				"phase_controller",
				0.4
			}
		}
	},
	{
		cueName = "bgm_activity_1_6_story_story",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 8,
		cuesheet = "bgm_activity_1_6_story_story",
		musicName = "Rêves d'intérieur",
		id = 96,
		awbName = "bgm_activity_1_6_story_story",
		detail = "作曲：Polymath9",
		initAISAC = {
			{
				"phase_controller",
				0
			}
		}
	},
	{
		cueName = "bgm_activity_1_6_story_story",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 8,
		cuesheet = "bgm_activity_1_6_story_story",
		musicName = "Rêves de rêves",
		id = 97,
		awbName = "bgm_activity_1_6_story_story",
		detail = "铸起高塔，自证存在后，蔑神之人不会就此止步。\n\n作曲：Polymath9",
		initAISAC = {
			{
				"phase_controller",
				0.2
			}
		}
	},
	{
		cueName = "bgm_activity_1_6_story_intense",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 8,
		cuesheet = "bgm_activity_1_6_story_intense",
		musicName = "Unsettling Corridor",
		id = 98,
		awbName = "bgm_activity_1_6_story_intense",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_6_park_theme",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 8,
		cuesheet = "bgm_activity_1_6_park_theme",
		musicName = "Valleyrand Park (Story ver.)",
		id = 99,
		awbName = "bgm_activity_1_6_park_theme",
		initAISAC = "",
		detail = "曲名：Valleyrand Park (Story ver.)\n作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_6_spring_ui",
		authorName = "Xin",
		ableBGM = 1,
		album = 8,
		cuesheet = "bgm_activity_1_6_spring_ui",
		musicName = "金瓯照影",
		id = 100,
		awbName = "bgm_activity_1_6_spring_ui",
		initAISAC = "",
		detail = "作曲：Xin"
	},
	{
		cueName = "bgm_activity_1_6_spring_restaurant",
		authorName = "Xin",
		ableBGM = 1,
		album = 8,
		cuesheet = "bgm_activity_1_6_spring_restaurant",
		musicName = "且笑桑田 (Ver. 1)",
		id = 101,
		awbName = "bgm_activity_1_6_spring_restaurant",
		detail = "作曲：Xin",
		initAISAC = {
			{
				"phase_controller",
				0
			}
		}
	},
	{
		cueName = "bgm_activity_1_6_spring_restaurant",
		authorName = "Xin",
		ableBGM = 1,
		album = 8,
		cuesheet = "bgm_activity_1_6_spring_restaurant",
		musicName = "且笑桑田 (Ver. 2)",
		id = 102,
		awbName = "bgm_activity_1_6_spring_restaurant",
		detail = "作曲：Xin",
		initAISAC = {
			{
				"phase_controller",
				0.5
			}
		}
	},
	{
		cueName = "bgm_activity_1_6_spring_boss",
		authorName = "Xin",
		ableBGM = 1,
		album = 8,
		cuesheet = "bgm_activity_1_6_spring_boss",
		musicName = "鼓焰鸣夕",
		id = 103,
		awbName = "bgm_activity_1_6_spring_boss",
		initAISAC = "",
		detail = "作曲：Xin"
	},
	{
		cueName = "bgm_activity_1_7_ui",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 9,
		cuesheet = "bgm_activity_1_7_ui",
		musicName = "Ominous Countdown",
		id = 104,
		awbName = "bgm_activity_1_7_ui",
		initAISAC = "",
		detail = "时钟倒数着火光中的审判。\n\n作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_7_battle_firehouse",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 9,
		cuesheet = "bgm_activity_1_7_battle_firehouse",
		musicName = "Trial in Flame",
		id = 105,
		awbName = "bgm_activity_1_7_battle_firehouse",
		initAISAC = "",
		detail = "「把你放出来，是因为一份责任；阻止你，也是因为相同的责任。」\n\n作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_1_7_story_firehouse",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 9,
		cuesheet = "bgm_activity_1_7_story_firehouse",
		musicName = "Imbalanced Revenge",
		id = 106,
		awbName = "bgm_activity_1_7_story_firehouse",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_promotion_2_0_yungexing_full",
		authorName = "呦猫UNEKO",
		ableBGM = 1,
		album = 10,
		cuesheet = "bgm_promotion_2_0_yungexing_full",
		musicName = "云歌行",
		id = 107,
		awbName = "bgm_promotion_2_0_yungexing_full",
		initAISAC = "",
		detail = "人间何事无由头，江河水自流。\n\n演唱：呦猫UNEKO\n作曲：Polymath9\n编曲：Polymath9 × VeetaCrush × S9ryne\n作词：大九_LN\n弦乐：国际首席爱乐乐团\n弦乐监制：李朋\n弦乐录音棚：九紫天诚录音棚\n弦乐录音师：刘婉秋\n混音：VeetaCrush\n母带：VeetaCrush\n制作：Polymath9@勇仕网络"
	},
	{
		cueName = "bgm_promotion_2_0_yungexing_game",
		authorName = "呦猫UNEKO",
		ableBGM = 1,
		album = 10,
		cuesheet = "bgm_promotion_2_0_yungexing_game",
		musicName = "云歌行 (激奏版)",
		id = 108,
		awbName = "bgm_promotion_2_0_yungexing_game",
		initAISAC = "",
		detail = "演唱：呦猫UNEKO\n作曲：Polymath9\n编曲：VeetaCrush × S9ryne feat. Polymath9\n作词：大九_LN\n混音：VeetaCrush\n母带：VeetaCrush\n制作：Polymath9@勇仕网络"
	},
	{
		cueName = "bgm_promotion_2_0_yungexing",
		authorName = "呦猫UNEKO",
		ableBGM = 1,
		album = 10,
		cuesheet = "bgm_promotion_2_0_yungexing",
		musicName = "云歌行 (前瞻版)",
		id = 109,
		awbName = "bgm_promotion_2_0_yungexing",
		initAISAC = "",
		detail = "演唱：呦猫UNEKO\n作曲：Polymath9\n编曲：Polymath9\n作词：大九_LN\n弦乐：国际首席爱乐乐团\n弦乐监制：李朋\n弦乐录音棚：记忆时刻录音棚\n弦乐录音师：肖广一\n混音：VeetaCrush\n母带：VeetaCrush\n制作：Polymath9@勇仕网络"
	},
	{
		cueName = "bgm_activity_2_0_ui",
		authorName = "Xin",
		ableBGM = 1,
		album = 10,
		cuesheet = "bgm_activity_2_0_ui",
		musicName = "坐看云起",
		id = 110,
		awbName = "bgm_activity_2_0_ui",
		initAISAC = "",
		detail = "行到水穷观山色，濛濛。旧事如潮天地中。\n\n作曲：Xin"
	},
	{
		cueName = "bgm_activity_2_0_battle_oldtown",
		authorName = "melo",
		ableBGM = 1,
		album = 10,
		cuesheet = "bgm_activity_2_0_battle_oldtown",
		musicName = "再起尘嚣",
		id = 111,
		awbName = "bgm_activity_2_0_battle_oldtown",
		initAISAC = "",
		detail = "作曲：melo"
	},
	{
		cueName = "bgm_activity_2_0_battle_jingdu",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 10,
		cuesheet = "bgm_activity_2_0_battle_jingdu",
		musicName = "形机变",
		id = 112,
		awbName = "bgm_activity_2_0_battle_jingdu",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_2_0_battle_jingdu_boss",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 10,
		cuesheet = "bgm_activity_2_0_battle_jingdu_boss",
		musicName = "却疾难",
		id = 113,
		awbName = "bgm_activity_2_0_battle_jingdu_boss",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_2_0_battle_tianlu",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 10,
		cuesheet = "bgm_activity_2_0_battle_tianlu",
		musicName = "既醉也",
		id = 114,
		awbName = "bgm_activity_2_0_battle_tianlu",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_2_0_story_oldtown",
		authorName = "melo",
		ableBGM = 1,
		album = 10,
		cuesheet = "bgm_activity_2_0_story_oldtown",
		musicName = "问旧年",
		id = 115,
		awbName = "bgm_activity_2_0_story_oldtown",
		initAISAC = "",
		detail = "作曲：melo"
	},
	{
		cueName = "bgm_activity_2_0_story_jingdu",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 10,
		cuesheet = "bgm_activity_2_0_story_jingdu",
		musicName = "见青山",
		id = 116,
		awbName = "bgm_activity_2_0_story_jingdu",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_2_0_story_tianlu",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 10,
		cuesheet = "bgm_activity_2_0_story_tianlu",
		musicName = "客如云",
		id = 117,
		awbName = "bgm_activity_2_0_story_tianlu",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_2_0_warchess",
		authorName = "melo",
		ableBGM = 1,
		album = 10,
		cuesheet = "bgm_activity_2_0_warchess",
		musicName = "自逍遥",
		id = 118,
		awbName = "bgm_activity_2_0_warchess",
		initAISAC = "",
		detail = "作曲：melo"
	},
	{
		cueName = "bgm_dorm_01",
		authorName = "M€I",
		ableBGM = 1,
		album = 10,
		cuesheet = "bgm_dorm_01",
		musicName = "A Glimpse of World",
		id = 119,
		awbName = "bgm_dorm_01",
		initAISAC = "",
		detail = "作曲：M€I"
	},
	{
		cueName = "bgm_activity_2_1_ui",
		authorName = "melo",
		ableBGM = 1,
		album = 11,
		cuesheet = "bgm_activity_2_1_ui",
		musicName = "逆断沧澜",
		id = 120,
		awbName = "bgm_activity_2_1_ui",
		initAISAC = "",
		detail = "洛水宵明坠灵枢，灵枢倾欹人殊途。\n作曲：melo"
	},
	{
		cueName = "bgm_activity_2_0_battle_source_xuheng",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 11,
		cuesheet = "bgm_activity_2_0_battle_source_xuheng",
		musicName = "衍神工",
		id = 121,
		awbName = "bgm_activity_2_0_battle_source_xuheng",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_2_1_battle_city",
		authorName = "melo",
		ableBGM = 1,
		album = 11,
		cuesheet = "bgm_activity_2_1_battle_city",
		musicName = "镇天阙",
		id = 122,
		awbName = "bgm_activity_2_1_battle_city",
		initAISAC = "",
		detail = "作曲：melo"
	},
	{
		cueName = "bgm_activity_2_1_battle_boss_4038_1",
		authorName = "VeetaCrush",
		ableBGM = 1,
		album = 11,
		cuesheet = "bgm_activity_2_1_battle_boss_4038_1",
		musicName = "双星·启原 - Binary Birth",
		id = 123,
		awbName = "bgm_activity_2_1_battle_boss_4038_1",
		initAISAC = "",
		detail = "「染血亦或蒙尘，我名唯此原初。」\n\n曲名：<color=#6567f1>双星·启原</color> - <color=#8e63f5>Binary Birth\n</color>作曲：VeetaCrush"
	},
	{
		cueName = "bgm_activity_2_1_battle_boss_4038_2",
		authorName = "S9ryne",
		ableBGM = 1,
		album = 11,
		cuesheet = "bgm_activity_2_1_battle_boss_4038_2",
		musicName = "双星·轮舞 - Binary Gyration",
		id = 124,
		awbName = "bgm_activity_2_1_battle_boss_4038_2",
		initAISAC = "",
		detail = "「所有人都在怀念有机会挽回失败的时候，所有人都对宿命裁定的未来熟视无睹。」\n\n曲名：<color=#6567f1>双星·轮舞</color> - <color=#8e63f5>Binary Gyration</color>\n作曲：S9ryne"
	},
	{
		cueName = "bgm_activity_2_1_battle_boss_4038_3",
		authorName = "Nevia feat. Polymath9",
		ableBGM = 1,
		album = 11,
		cuesheet = "bgm_activity_2_1_battle_boss_4038_3",
		musicName = "双星·热寂 - Binary Oblivion",
		id = 125,
		awbName = "bgm_activity_2_1_battle_boss_4038_3",
		initAISAC = "",
		detail = "「我们拥有的选择很多，可最后真正能去做的事却很少。性命相托的坚持，有一个就够了。」\n\n曲名：<color=#6567f1>双星·热寂</color> - <color=#8e63f5>Binary Oblivion</color>\n作曲：Nevia feat. Polymath9\n编曲：Nevia"
	},
	{
		cueName = "bgm_activity_2_0_story_source_xuheng",
		authorName = "M€I",
		ableBGM = 1,
		album = 11,
		cuesheet = "bgm_activity_2_0_story_source_xuheng",
		musicName = "涉九渊",
		id = 126,
		awbName = "bgm_activity_2_0_story_source_xuheng",
		initAISAC = "",
		detail = "作曲：M€I"
	},
	{
		cueName = "bgm_activity_2_1_story_sifangyuan",
		authorName = "melo",
		ableBGM = 1,
		album = 11,
		cuesheet = "bgm_activity_2_1_story_sifangyuan",
		musicName = "晏山河",
		id = 127,
		awbName = "bgm_activity_2_1_story_sifangyuan",
		initAISAC = "",
		detail = "作曲：melo"
	},
	{
		cueName = "bgm_activity_2_1_story_city",
		authorName = "melo",
		ableBGM = 1,
		album = 11,
		cuesheet = "bgm_activity_2_1_story_city",
		musicName = "越阡陌",
		id = 128,
		awbName = "bgm_activity_2_1_story_city",
		initAISAC = "",
		detail = "作曲：melo"
	},
	{
		cueName = "bgm_activity_2_1_story_farewell",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 11,
		cuesheet = "bgm_activity_2_1_story_farewell",
		musicName = "胡不归",
		id = 129,
		awbName = "bgm_activity_2_1_story_farewell",
		initAISAC = "",
		detail = "暮落咫尺斜千里，无言长恨不忍离。\n\n作曲：Polymath9\n弦乐：国际首席爱乐乐团\n乐团艺术总监：李朋\n弦乐录音棚：金田录音棚\n录音师：王小四\n混音：VeetaCrush"
	},
	{
		cueName = "bgm_activity_2_1_story_beforebattle",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 11,
		cuesheet = "bgm_activity_2_1_story_beforebattle",
		musicName = "问终尽",
		id = 130,
		awbName = "bgm_activity_2_1_story_beforebattle",
		initAISAC = "",
		detail = "作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_2_1_story_afterbattle",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 11,
		cuesheet = "bgm_activity_2_1_story_afterbattle",
		musicName = "应作吾",
		id = 131,
		awbName = "bgm_activity_2_1_story_afterbattle",
		initAISAC = "",
		detail = "作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_2_1_minigame_connect",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 11,
		cuesheet = "bgm_activity_2_1_minigame_connect",
		musicName = "万象同鸣",
		id = 132,
		awbName = "bgm_activity_2_1_minigame_connect",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_2_2_battle_boss_4036_2",
		authorName = "祈Inory",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_battle_boss_4036_2",
		musicName = "Promise (2023 Mix)",
		id = 133,
		awbName = "bgm_activity_2_2_battle_boss_4036_2",
		detail = "哪怕只有这一次也好，就让我用上所有力气吧，让我握住你的手，站在你前面，然后……在有你的未来再见吧，约好了。\n\n曲名：Promise (2023 Mix)\n演唱：祈Inory\n作曲：Polymath9\n编曲/人声和声：VeetaCrush\n作词：TetraCalyx",
		initAISAC = {
			{
				"phase_controller",
				1
			}
		}
	},
	{
		cueName = "bgm_activity_2_2_battle_boss_4036_2",
		authorName = "VeetaCrush",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_battle_boss_4036_2",
		musicName = "Promise (2023 Mix) (Inst. Ver.)",
		id = 134,
		awbName = "bgm_activity_2_2_battle_boss_4036_2",
		detail = "曲名：Promise (2023 Mix) (Inst. Ver.)\n作曲：VeetaCrush",
		initAISAC = {
			{
				"phase_controller",
				0
			}
		}
	},
	{
		cueName = "bgm_activity_2_2_ui",
		authorName = "melo",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_ui",
		musicName = "饮剑重霄",
		id = 135,
		awbName = "bgm_activity_2_2_ui",
		initAISAC = "",
		detail = "重霄一剑斩长夜，破云清光照永劫。\n\n作曲：melo"
	},
	{
		cueName = "bgm_activity_2_2_story_tiantongyinqing",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_story_tiantongyinqing",
		musicName = "通六合",
		id = 136,
		awbName = "bgm_activity_2_2_story_tiantongyinqing",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_2_2_battle_tiantongyinqing",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_battle_tiantongyinqing",
		musicName = "揽乾坤",
		id = 137,
		awbName = "bgm_activity_2_2_battle_tiantongyinqing",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_2_2_story_ruomuhuajing",
		authorName = "melo",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_story_ruomuhuajing",
		musicName = "墨下春秋",
		id = 138,
		awbName = "bgm_activity_2_2_story_ruomuhuajing",
		initAISAC = "",
		detail = "作曲：melo"
	},
	{
		cueName = "bgm_activity_2_2_battle_ruomuhuajing",
		authorName = "melo",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_battle_ruomuhuajing",
		musicName = "太虚淋漓",
		id = 139,
		awbName = "bgm_activity_2_2_battle_ruomuhuajing",
		initAISAC = "",
		detail = "作曲：melo"
	},
	{
		cueName = "bgm_activity_2_2_battle_boss_4036_1",
		authorName = "S9ryne",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_battle_boss_4036_1",
		musicName = "失落彼岸 - Wildered Lycoris",
		id = 140,
		awbName = "bgm_activity_2_2_battle_boss_4036_1",
		initAISAC = "",
		detail = "于现实的幻象中迷失的人啊，请聆听终末的寂静，拥抱不协的凋零，等待完美的重生。\n\n曲名：失落彼岸 - Wildered Lycoris\n作曲：S9ryne"
	},
	{
		cueName = "bgm_activity_2_2_battle_boss_4037_1",
		authorName = "S9ryne feat. Polymath9",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_battle_boss_4037_1",
		musicName = "启示·降临 - Paradoxical Nemesis",
		id = 141,
		awbName = "bgm_activity_2_2_battle_boss_4037_1",
		initAISAC = "",
		detail = "一切的答案藏于起源，一切的意义来自真相。启示为上，剥夺世界腐朽的伪装。\n\n曲名：启示·降临 - Paradoxical Nemesis\n作曲：S9ryne feat. Polymath9\n编曲：S9ryne"
	},
	{
		cueName = "bgm_activity_2_2_battle_boss_4037_2",
		authorName = "S9ryne feat. Polymath9",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_battle_boss_4037_2",
		musicName = "启示·混沌 - Unrevealed Chaos",
		id = 142,
		awbName = "bgm_activity_2_2_battle_boss_4037_2",
		initAISAC = "",
		detail = "曲名：启示·混沌 - Unrevealed Chaos\n作曲：S9ryne feat. Polymath9\n编曲：S9ryne"
	},
	{
		cueName = "bgm_activity_2_2_battle_boss_4037_chase",
		authorName = "HJLL & S9ryne",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_battle_boss_4037_chase",
		musicName = "启示·超限 - Transfinite Distance",
		id = 143,
		awbName = "bgm_activity_2_2_battle_boss_4037_chase",
		initAISAC = "",
		detail = "曲名：启示·超限 - Transfinite Distance\n作曲：HJLL & S9ryne"
	},
	{
		cueName = "bgm_activity_2_2_minigame_cruise",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_minigame_cruise",
		musicName = "Stýri-Maðr Skaði",
		id = 144,
		awbName = "bgm_activity_2_2_minigame_cruise",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_2_2_minigame_watergun",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_minigame_watergun",
		musicName = "Splash Championship",
		id = 145,
		awbName = "bgm_activity_2_2_minigame_watergun",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_2_2_story_ver_1",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_story_ver_1",
		musicName = "(Un)forgotten Promise",
		id = 146,
		awbName = "bgm_activity_2_2_story_ver_1",
		initAISAC = "",
		detail = "说好了会变得勇敢，说好了永远不会忘记，说好了太多太多的事情……我一直都记得，自己有多么想，多么想要守护……与你的那些约定。\n\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_2_2_story_ver_1_short",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_story_ver_1_short",
		musicName = "(Un)forgotten Promise (Short Ver.)",
		id = 147,
		awbName = "bgm_activity_2_2_story_ver_1_short",
		initAISAC = "",
		detail = "曲名：(Un)forgotten Promise (Short Ver.)\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_2_2_story_promise_orgel",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_story_promise_orgel",
		musicName = "Promise (Orgel Ver.)",
		id = 148,
		awbName = "bgm_activity_2_2_story_promise_orgel",
		initAISAC = "",
		detail = "作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_2_2_story_ygx",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_story_ygx",
		musicName = "云歌徐行",
		id = 149,
		awbName = "bgm_activity_2_2_story_ygx",
		initAISAC = "",
		detail = "相遇时远终有别离，前路徐行莫问归期。\n\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_2_2_story_meeting",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_story_meeting",
		musicName = "Clear NIL Up",
		id = 150,
		awbName = "bgm_activity_2_2_story_meeting",
		initAISAC = "",
		detail = "坐下来，喝杯茶，算算旧账，换换心情。\n没有不见光的秘密，也没有不能谈的问题。\n——喝了杯茶，一切从头开始，一切还没过去。\n\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_2_2_story_talk",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 12,
		cuesheet = "bgm_activity_2_2_story_talk",
		musicName = "Intro: 22A1FB9A",
		id = 151,
		awbName = "bgm_activity_2_2_story_talk",
		initAISAC = "",
		detail = "我们都在寻找另一个的自己。\n藏起的、分开的、迷路的、陌生的。\n我们都在寻找完整的自己。\n终究会成长，去补全我们的无能为力。\n我们……永远是我，永远是你。\n\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_2_4_ui",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 13,
		cuesheet = "bgm_activity_2_4_ui",
		musicName = "Sequestered Rite",
		id = 152,
		awbName = "bgm_activity_2_4_ui",
		initAISAC = "",
		detail = "草叶倾折，小鹿远去，脚印无回。\n\n作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_2_4_battle_forest",
		authorName = "melo",
		ableBGM = 1,
		album = 13,
		cuesheet = "bgm_activity_2_4_battle_forest",
		musicName = "Incessant Contagion",
		id = 153,
		awbName = "bgm_activity_2_4_battle_forest",
		initAISAC = "",
		detail = "作曲：melo"
	},
	{
		cueName = "bgm_activity_2_4_battle_xiajingqu",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 13,
		cuesheet = "bgm_activity_2_4_battle_xiajingqu",
		musicName = "Through the Crowd",
		id = 154,
		awbName = "bgm_activity_2_4_battle_xiajingqu",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_2_4_battle_wall",
		authorName = "melo",
		ableBGM = 1,
		album = 13,
		cuesheet = "bgm_activity_2_4_battle_wall",
		musicName = "We're the Wall",
		id = 155,
		awbName = "bgm_activity_2_4_battle_wall",
		initAISAC = "",
		detail = "作曲：melo"
	},
	{
		cueName = "bgm_activity_2_4_battle_boss_4030",
		authorName = "Nevia",
		ableBGM = 1,
		album = 13,
		cuesheet = "bgm_activity_2_4_battle_boss_4030",
		musicName = "Decay Is Thriving",
		id = 156,
		awbName = "bgm_activity_2_4_battle_boss_4030",
		initAISAC = "",
		detail = "在泥土中蔓延，在朽寂中苏生。\n\n作曲：Nevia"
	},
	{
		cueName = "bgm_activity_2_4_story_forest",
		authorName = "melo",
		ableBGM = 1,
		album = 13,
		cuesheet = "bgm_activity_2_4_story_forest",
		musicName = "Germinating Shadow",
		id = 157,
		awbName = "bgm_activity_2_4_story_forest",
		initAISAC = "",
		detail = "作曲：melo"
	},
	{
		cueName = "bgm_activity_2_4_story_xiajingqu",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 13,
		cuesheet = "bgm_activity_2_4_story_xiajingqu",
		musicName = "Among the Crowd",
		id = 158,
		awbName = "bgm_activity_2_4_story_xiajingqu",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_2_4_story_wall",
		authorName = "melo",
		ableBGM = 1,
		album = 13,
		cuesheet = "bgm_activity_2_4_story_wall",
		musicName = "Watch the Horizon",
		id = 159,
		awbName = "bgm_activity_2_4_story_wall",
		initAISAC = "",
		detail = "作曲：melo"
	},
	{
		cueName = "bgm_activity_2_4_story_firework",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 13,
		cuesheet = "bgm_activity_2_4_story_firework",
		musicName = "Inochi no Hanabi",
		id = 160,
		awbName = "bgm_activity_2_4_story_firework",
		initAISAC = "",
		detail = "我想绽放，哪怕只有一瞬。\n\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_2_6_ui_vocal",
		authorName = "小时姑娘",
		ableBGM = 1,
		album = 14,
		cuesheet = "bgm_activity_2_6_ui_vocal",
		musicName = "Spring's Banquet",
		id = 161,
		awbName = "bgm_activity_2_6_ui_vocal",
		initAISAC = "",
		detail = "孤影独徘，阡陌何尽，春光倾处。\n\n演唱：小时姑娘\n作曲：Polymath9\n编曲：Polymath9 feat. HJLL\n作词：大九_LN\n录音棚：SoundHouse Studio·星光盒子录音室\n录音：杨婉芸\n人声编辑：杨婉芸\n混音：VeetaCrush"
	},
	{
		cueName = "bgm_activity_2_6_ui",
		authorName = "Polymath9 feat. HJLL",
		ableBGM = 1,
		album = 14,
		cuesheet = "bgm_activity_2_6_ui",
		musicName = "Spring's Banquet (Inst. Ver.)",
		id = 162,
		awbName = "bgm_activity_2_6_ui",
		initAISAC = "",
		detail = "曲名：Spring's Banquet (Inst. Ver.)\n作曲：Polymath9\n编曲：Polymath9 feat. HJLL\n混音：VeetaCrush"
	},
	{
		cueName = "bgm_activity_2_6_minigame_kagutsuchi",
		authorName = "Xin",
		ableBGM = 1,
		album = 14,
		cuesheet = "bgm_activity_2_6_minigame_kagutsuchi",
		musicName = "Hamon no Yume",
		id = 163,
		awbName = "bgm_activity_2_6_minigame_kagutsuchi",
		initAISAC = "",
		detail = "作曲：Xin"
	},
	{
		cueName = "bgm_activity_2_6_battle_karasugo_garden",
		authorName = "天游",
		ableBGM = 1,
		album = 14,
		cuesheet = "bgm_activity_2_6_battle_karasugo_garden",
		musicName = "Inaudible Crow",
		id = 164,
		awbName = "bgm_activity_2_6_battle_karasugo_garden",
		initAISAC = "",
		detail = "作曲：天游"
	},
	{
		cueName = "bgm_activity_2_6_battle_karasugo_tokoyo",
		authorName = "Nevia & Project-G",
		ableBGM = 1,
		album = 14,
		cuesheet = "bgm_activity_2_6_battle_karasugo_tokoyo",
		musicName = "Deranged Circuit",
		id = 165,
		awbName = "bgm_activity_2_6_battle_karasugo_tokoyo",
		initAISAC = "",
		detail = "你必须了解，你必须无知，你必须找到规则，你必须破坏规则。\n你不能离开。\n\n作曲：Nevia & Project-G"
	},
	{
		cueName = "bgm_activity_2_6_battle_biwuchang",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 14,
		cuesheet = "bgm_activity_2_6_battle_biwuchang",
		musicName = "Blazing",
		id = 166,
		awbName = "bgm_activity_2_6_battle_biwuchang",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_2_6_battle_boss_4039",
		authorName = "S9ryne",
		ableBGM = 1,
		album = 14,
		cuesheet = "bgm_activity_2_6_battle_boss_4039",
		musicName = "Undying Prophecy",
		id = 167,
		awbName = "bgm_activity_2_6_battle_boss_4039",
		detail = "因破碎而塑造，因谎言而真实。\n\n作曲：S9ryne",
		initAISAC = {
			{
				"phase_controller",
				0
			}
		}
	},
	{
		cueName = "bgm_activity_2_6_battle_boss_4039",
		authorName = "S9ryne",
		ableBGM = 1,
		album = 14,
		cuesheet = "bgm_activity_2_6_battle_boss_4039",
		musicName = "Unfading Mirage",
		id = 168,
		awbName = "bgm_activity_2_6_battle_boss_4039",
		detail = "作曲：S9ryne",
		initAISAC = {
			{
				"phase_controller",
				1
			}
		}
	},
	{
		cueName = "bgm_activity_2_6_story_karasugo_garden",
		authorName = "天游",
		ableBGM = 1,
		album = 14,
		cuesheet = "bgm_activity_2_6_story_karasugo_garden",
		musicName = "Invisible Plume",
		id = 169,
		awbName = "bgm_activity_2_6_story_karasugo_garden",
		initAISAC = "",
		detail = "作曲：天游"
	},
	{
		cueName = "bgm_activity_2_6_story_karasugo_tokoyo",
		authorName = "Nevia",
		ableBGM = 1,
		album = 14,
		cuesheet = "bgm_activity_2_6_story_karasugo_tokoyo",
		musicName = "Chaotic Verity",
		id = 170,
		awbName = "bgm_activity_2_6_story_karasugo_tokoyo",
		initAISAC = "",
		detail = "作曲：Nevia"
	},
	{
		cueName = "bgm_activity_2_6_story_biwuchang",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 14,
		cuesheet = "bgm_activity_2_6_story_biwuchang",
		musicName = "Calcining",
		id = 171,
		awbName = "bgm_activity_2_6_story_biwuchang",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_2_6_story_sasanami_quiet",
		authorName = "Polymath9 feat. CoyDe",
		ableBGM = 1,
		album = 14,
		cuesheet = "bgm_activity_2_6_story_sasanami_quiet",
		musicName = "Taiyou o Saegiru",
		id = 172,
		awbName = "bgm_activity_2_6_story_sasanami_quiet",
		initAISAC = "",
		detail = "作曲：Polymath9 feat. CoyDe\n编曲：Polymath9"
	},
	{
		cueName = "bgm_activity_2_7_story_death",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 14,
		cuesheet = "bgm_activity_2_7_story_death",
		musicName = "Humanus, Nomen est",
		id = 173,
		awbName = "bgm_activity_2_7_story_death",
		initAISAC = "",
		detail = "「不要祈祷，神明也无法拯救我们。」\n「不要退缩，我们与神明并肩作战。」\n\n作曲：Polymath9\n混音：LousikAEy"
	},
	{
		cueName = "bgm_activity_2_6_story_izanami_piano",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 14,
		cuesheet = "bgm_activity_2_6_story_izanami_piano",
		musicName = "Spring's Banquet (Another Ver.)",
		id = 174,
		awbName = "bgm_activity_2_6_story_izanami_piano",
		initAISAC = "",
		detail = "在某个清晨，女孩主动将自己吊死在集市的入口。\n\n曲名：Spring's Banquet (Another Ver.)\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_2_8_ui",
		authorName = "melo",
		ableBGM = 1,
		album = 15,
		cuesheet = "bgm_activity_2_8_ui",
		musicName = "Trudge Up My Creed",
		id = 175,
		awbName = "bgm_activity_2_8_ui",
		initAISAC = "",
		detail = "以能载心，以志劳心，以德守心。夫此三用，再无移易，道心不外如是。\n\n作曲：melo"
	},
	{
		cueName = "bgm_activity_2_8_battle_jivitabad_slum",
		authorName = "D.Yi",
		ableBGM = 1,
		album = 15,
		cuesheet = "bgm_activity_2_8_battle_jivitabad_slum",
		musicName = "Ashen Mud",
		id = 176,
		awbName = "bgm_activity_2_8_battle_jivitabad_slum",
		initAISAC = "",
		detail = "作曲：D.Yi"
	},
	{
		cueName = "bgm_activity_2_8_battle_tara_garden",
		authorName = "天游",
		ableBGM = 1,
		album = 15,
		cuesheet = "bgm_activity_2_8_battle_tara_garden",
		musicName = "Jail on Hostility",
		id = 177,
		awbName = "bgm_activity_2_8_battle_tara_garden",
		initAISAC = "",
		detail = "作曲：天游"
	},
	{
		cueName = "bgm_activity_2_8_battle_tara_building",
		authorName = "HJLL",
		ableBGM = 1,
		album = 15,
		cuesheet = "bgm_activity_2_8_battle_tara_building",
		musicName = "Degrading Soma",
		id = 178,
		awbName = "bgm_activity_2_8_battle_tara_building",
		initAISAC = "",
		detail = "作曲：HJLL"
	},
	{
		cueName = "bgm_activity_2_8_battle_boss_4032",
		authorName = "Nevia & S9ryne",
		ableBGM = 1,
		album = 15,
		cuesheet = "bgm_activity_2_8_battle_boss_4032",
		musicName = "Duellum Zabolicum",
		id = 179,
		awbName = "bgm_activity_2_8_battle_boss_4032",
		initAISAC = "",
		detail = "只有在擂台上，正义与邪恶互道公平。\n\n作曲：Nevia & S9ryne"
	},
	{
		cueName = "bgm_activity_2_8_story_meruism",
		authorName = "D.Yi",
		ableBGM = 1,
		album = 15,
		cuesheet = "bgm_activity_2_8_story_meruism",
		musicName = "Lotus Illuminat Inanitatem",
		id = 180,
		awbName = "bgm_activity_2_8_story_meruism",
		initAISAC = "",
		detail = "祂赐予我们花朵，开满太阳与土地，填补创世的缺遗。\n\n曲名：Lotus Illuminat Inanitatem\n作曲：D.Yi"
	},
	{
		cueName = "bgm_activity_2_8_story_jivitabad_slum",
		authorName = "D.Yi",
		ableBGM = 1,
		album = 15,
		cuesheet = "bgm_activity_2_8_story_jivitabad_slum",
		musicName = "Slum Dog",
		id = 181,
		awbName = "bgm_activity_2_8_story_jivitabad_slum",
		initAISAC = "",
		detail = "作曲：D.Yi"
	},
	{
		cueName = "bgm_activity_2_8_story_tara_garden",
		authorName = "天游",
		ableBGM = 1,
		album = 15,
		cuesheet = "bgm_activity_2_8_story_tara_garden",
		musicName = "Inorganic Swamp",
		id = 182,
		awbName = "bgm_activity_2_8_story_tara_garden",
		initAISAC = "",
		detail = "作曲：天游"
	},
	{
		cueName = "bgm_activity_2_8_story_tara_building",
		authorName = "HJLL",
		ableBGM = 1,
		album = 15,
		cuesheet = "bgm_activity_2_8_story_tara_building",
		musicName = "Bioenergy Source",
		id = 183,
		awbName = "bgm_activity_2_8_story_tara_building",
		initAISAC = "",
		detail = "作曲：HJLL"
	},
	{
		cueName = "bgm_activity_2_8_minigame_valentine",
		authorName = "LousikAEy feat. Polymath9",
		ableBGM = 1,
		album = 15,
		cuesheet = "bgm_activity_2_8_minigame_valentine",
		musicName = "Dancing to the Moon",
		id = 184,
		awbName = "bgm_activity_2_8_minigame_valentine",
		initAISAC = "",
		detail = "作曲：LousikAEy feat. Polymath9\n编曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_2_9_minigame_spring",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 15,
		cuesheet = "bgm_activity_2_9_minigame_spring",
		musicName = "问雪寻春",
		id = 185,
		awbName = "bgm_activity_2_9_minigame_spring",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_side_daily07",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 15,
		cuesheet = "bgm_side_daily07",
		musicName = "Lingering Memories",
		id = 186,
		awbName = "bgm_side_daily07",
		initAISAC = "",
		detail = "作曲：Polymath9\n混音：LousikAEy"
	},
	{
		cueName = "bgm_activity_2_10_ui",
		authorName = "Street",
		ableBGM = 1,
		album = 16,
		cuesheet = "bgm_activity_2_10_ui",
		musicName = "Sakura no Saisei",
		id = 187,
		awbName = "bgm_activity_2_10_ui",
		initAISAC = "",
		detail = "气移樱动，剑起心归，意至天绝。\n\n作曲：Street"
	},
	{
		cueName = "bgm_activity_2_10_battle_reiten",
		authorName = "Street",
		ableBGM = 1,
		album = 16,
		cuesheet = "bgm_activity_2_10_battle_reiten",
		musicName = "Drifting Without Wind",
		id = 188,
		awbName = "bgm_activity_2_10_battle_reiten",
		initAISAC = "",
		detail = "作曲：Street"
	},
	{
		cueName = "bgm_activity_2_10_battle_sasanamijyou",
		authorName = "Street",
		ableBGM = 1,
		album = 16,
		cuesheet = "bgm_activity_2_10_battle_sasanamijyou",
		musicName = "Mutated Heaven",
		id = 189,
		awbName = "bgm_activity_2_10_battle_sasanamijyou",
		initAISAC = "",
		detail = "作曲：Street"
	},
	{
		cueName = "bgm_activity_2_10_battle_visbane_factory",
		authorName = "Street",
		ableBGM = 1,
		album = 16,
		cuesheet = "bgm_activity_2_10_battle_visbane_factory",
		musicName = "Assembly Darkness",
		id = 190,
		awbName = "bgm_activity_2_10_battle_visbane_factory",
		initAISAC = "",
		detail = "作曲：Street"
	},
	{
		cueName = "bgm_activity_2_10_battle_sasanami_photonrail",
		authorName = "Street",
		ableBGM = 1,
		album = 16,
		cuesheet = "bgm_activity_2_10_battle_sasanami_photonrail",
		musicName = "Penetrating the Crux",
		id = 191,
		awbName = "bgm_activity_2_10_battle_sasanami_photonrail",
		initAISAC = "",
		detail = "作曲：Street"
	},
	{
		cueName = "bgm_activity_2_10_battle_boss_4022",
		authorName = "Street",
		ableBGM = 1,
		album = 16,
		cuesheet = "bgm_activity_2_10_battle_boss_4022",
		musicName = "天下独尊 - Tenka Dokuson",
		id = 192,
		awbName = "bgm_activity_2_10_battle_boss_4022",
		initAISAC = "",
		detail = "「人类总是需要相信些什么才能活下去，脆弱又卑怯地盼望着神明的庇佑。现在，他们渺小的愿望就要实现了。」\n\n曲名：天下独尊 - Tenka Dokuson\n作曲：Street"
	},
	{
		cueName = "bgm_activity_2_10_battle_boss_4016",
		authorName = "Street",
		ableBGM = 1,
		album = 16,
		cuesheet = "bgm_activity_2_10_battle_boss_4016",
		musicName = "天上诛灭 - Tenjou Chuumetsu",
		id = 193,
		awbName = "bgm_activity_2_10_battle_boss_4016",
		initAISAC = "",
		detail = "「人类不需要神明来照亮天空。人类，有属于自己的光芒。」\n\n曲名：天上诛灭 - Tenjou Chuumetsu\n作曲：Street"
	},
	{
		cueName = "bgm_activity_2_10_story_reiten",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 16,
		cuesheet = "bgm_activity_2_10_story_reiten",
		musicName = "Walking Without Path",
		id = 194,
		awbName = "bgm_activity_2_10_story_reiten",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_2_10_story_sasanamijyou",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 16,
		cuesheet = "bgm_activity_2_10_story_sasanamijyou",
		musicName = "Hidden Heaven",
		id = 195,
		awbName = "bgm_activity_2_10_story_sasanamijyou",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_2_10_story_visbane_factory",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 16,
		cuesheet = "bgm_activity_2_10_story_visbane_factory",
		musicName = "Stationary Darkness",
		id = 196,
		awbName = "bgm_activity_2_10_story_visbane_factory",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_2_10_story_sasanami_photonrail",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 16,
		cuesheet = "bgm_activity_2_10_story_sasanami_photonrail",
		musicName = "Unraveling the Crux",
		id = 197,
		awbName = "bgm_activity_2_10_story_sasanami_photonrail",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_2_10_story_buzenbo",
		authorName = "Street/Polymath9",
		ableBGM = 1,
		album = 16,
		cuesheet = "bgm_activity_2_10_story_buzenbo",
		musicName = "Sakura no Saisei (Piano Ver.)",
		id = 198,
		awbName = "bgm_activity_2_10_story_buzenbo",
		initAISAC = "",
		detail = "残樱还尘，千年复开。\n\n曲名：Sakura no Saisei (Piano Ver.)\n作曲：Street\n钢琴改编：Polymath9"
	},
	{
		cueName = "bgm_activity_2_10_story_sekhmet",
		authorName = "Polymath9/LousikAEy",
		ableBGM = 1,
		album = 16,
		cuesheet = "bgm_activity_2_10_story_sekhmet",
		musicName = "Humanus, Nomen erit",
		id = 199,
		awbName = "bgm_activity_2_10_story_sekhmet",
		initAISAC = "",
		detail = "用生命的残响忏悔吧——漠视人类的你，最终败给了人类的力量。\n\n作曲：Polymath9\n编曲：Polymath9/LousikAEy"
	},
	{
		cueName = "bgm_activity_2_10_minigame_special",
		authorName = "Street",
		ableBGM = 1,
		album = 16,
		cuesheet = "bgm_activity_2_10_minigame_special",
		musicName = "Sakura Fubuki",
		id = 200,
		awbName = "bgm_activity_2_10_minigame_special",
		initAISAC = "",
		detail = "嗨嗨嗨，各位观众都听过楚门娱乐的新专了吗？我的评价是滑坡，继续滑坡，一泻千里！二十四世纪的乐坛真是每况愈下，是时候由本电台带各位重温三百年前的经典了。\n\n作曲：Street"
	},
	{
		cueName = "bgm_main_02",
		authorName = "moto & Haloweak",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_main_02",
		musicName = "Ethereal Aurora",
		id = 201,
		awbName = "bgm_main_02",
		initAISAC = "",
		detail = "作曲：moto & Haloweak"
	},
	{
		cueName = "bgm_count_2",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 1,
		cuesheet = "bgm_victory_count_2",
		musicName = "Next Victory",
		id = 202,
		awbName = "bgm_victory_count_2",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_promotion_3_0_mpf",
		authorName = "祈Inory",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_promotion_3_0_mpf",
		musicName = "My Precious Friend",
		id = 203,
		awbName = "bgm_promotion_3_0_mpf",
		initAISAC = "",
		detail = "愿每个人生命中都能遇见最好的彼此。\n\n曲名：My Precious Friend\n演唱：祈Inory\n作曲：Polymath9\n编曲：VeetaCrush\n作词：大九_LN\n电吉他：Nevia"
	},
	{
		cueName = "bgm_promotion_3_0_mpf_inst",
		authorName = "VeetaCrush feat. Polymath9",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_promotion_3_0_mpf_inst",
		musicName = "My Precious Friend (Inst. Ver.)",
		id = 204,
		awbName = "bgm_promotion_3_0_mpf_inst",
		initAISAC = "",
		detail = "曲名：My Precious Friend (Inst. Ver.)\n作曲：VeetaCrush feat. Polymath9\n编曲：VeetaCrush\n电吉他：Nevia"
	},
	{
		cueName = "bgm_activity_3_0_ui",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_ui",
		musicName = "Above Sapphire Horizon",
		id = 205,
		awbName = "bgm_activity_3_0_ui",
		initAISAC = "",
		detail = "在她澄澈的眼瞳中映出的，是幻象，是过往，还是地平线上升起的稀薄但温暖的曙光。\n\n曲名：Above Sapphire Horizon\n副标题：于蔚蓝的地平线上\n作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_0_ui_changable",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_ui",
		musicName = "Inside Slate Bubble",
		id = 206,
		awbName = "bgm_activity_3_0_ui_changable",
		detail = "曲名：Inside Slate Bubble\n作曲：LousikAEy",
		initAISAC = {
			{
				"phase_controller",
				1
			}
		}
	},
	{
		cueName = "bgm_activity_3_0_battle_northblock",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_battle_northblock",
		musicName = "Ruins of the Town",
		id = 207,
		awbName = "bgm_activity_3_0_battle_northblock",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_3_0_battle_forbidden_space",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_battle_forbidden_space",
		musicName = "Everlasting-exist Hymn",
		id = 208,
		awbName = "bgm_activity_3_0_battle_forbidden_space",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_3_0_story_northblock",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_northblock",
		musicName = "Remains of the Town",
		id = 209,
		awbName = "bgm_activity_3_0_story_northblock",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_3_0_story_forbidden_space",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_forbidden_space",
		musicName = "Everlasting-void Psalter",
		id = 210,
		awbName = "bgm_activity_3_0_story_forbidden_space",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_3_0_battle_south_outside",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_battle_south_outside",
		musicName = "Vivid Emulation",
		id = 211,
		awbName = "bgm_activity_3_0_battle_south_outside",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_0_battle_south_inside",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_battle_south_inside",
		musicName = "Glassy Reflection",
		id = 212,
		awbName = "bgm_activity_3_0_battle_south_inside",
		initAISAC = "",
		detail = "作曲：LousikAEy/Polymath9\n编曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_0_battle_boss_4040",
		authorName = "S9ryne",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_battle_boss_4040",
		musicName = "GAMER NO.10",
		id = 213,
		awbName = "bgm_activity_3_0_battle_boss_4040",
		initAISAC = "",
		detail = "这场游戏，只有活下来的才是胜者。\n\n作曲：S9ryne"
	},
	{
		cueName = "bgm_activity_3_0_battle_boss_4041",
		authorName = "HJLL",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_battle_boss_4041",
		musicName = "Branch Ruler",
		id = 214,
		awbName = "bgm_activity_3_0_battle_boss_4041",
		initAISAC = "",
		detail = "盖亚只有秩序，秩序没有情感，它支配却漠不关心，就像那轮虚幻的太阳。\n\n作曲：HJLL"
	},
	{
		cueName = "bgm_activity_3_0_story_special_tallina",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_special_tallina",
		musicName = "rainy, rainy, osmanthus.",
		id = 215,
		awbName = "bgm_activity_3_0_story_special_tallina",
		initAISAC = "",
		detail = "院子里的桂花开在她的每个秋天，落在她的眼里和心里，于是她看见了，金色飘散在有她的每一片天空与大地。\n\n曲名：rainy, rainy, osmanthus.\n副标题：Main Theme: 22A1FB9A\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_0_story_daily_leisure",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_daily_leisure",
		musicName = "Morland‘s Autumn",
		id = 216,
		awbName = "bgm_activity_3_0_story_daily_leisure",
		initAISAC = "",
		detail = "作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_0_story_intense_piano",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_intense_piano",
		musicName = "Sensitive Corner",
		id = 217,
		awbName = "bgm_activity_3_0_story_intense_piano",
		initAISAC = "",
		detail = "作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_0_story_daily_quiet",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_daily_quiet",
		musicName = "Gentle Sidewalk",
		id = 218,
		awbName = "bgm_activity_3_0_story_daily_quiet",
		initAISAC = "",
		detail = "作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_0_story_moon",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_moon",
		musicName = "Dream on the Moon",
		id = 219,
		awbName = "bgm_activity_3_0_story_moon",
		initAISAC = "",
		detail = "以此挽留书卷和梦里的月光。\n\n曲名：Dream on the Moon\n副标题：月之归处\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_0_story_data",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_data",
		musicName = "Protospace",
		id = 220,
		awbName = "bgm_activity_3_0_story_data",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_0_story_hospital",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_hospital",
		musicName = "Our Path to Home",
		id = 221,
		awbName = "bgm_activity_3_0_story_hospital",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_0_story_sad",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_sad",
		musicName = "Lost Moments",
		id = 222,
		awbName = "bgm_activity_3_0_story_sad",
		initAISAC = "",
		detail = "作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_0_story_quiet",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_quiet",
		musicName = "Story Flowing to Next Page",
		id = 223,
		awbName = "bgm_activity_3_0_story_quiet",
		initAISAC = "",
		detail = "曲名：Story Flowing to Next Page\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_0_story_hospital_room",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_hospital_room",
		musicName = "A Heartbeat Away",
		id = 224,
		awbName = "bgm_activity_3_0_story_hospital_room",
		initAISAC = "",
		detail = "作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_0_story_special_seaside",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_special_seaside",
		musicName = "Wordless Song for a Starry Night",
		id = 225,
		awbName = "bgm_activity_3_0_story_special_seaside",
		initAISAC = "",
		detail = "这不是故事的起点，也不会被这个世界记住。这只是一个平凡的夜晚中，孩子们将会珍藏一生的小小回忆。\n\n曲名：Wordless Song for a Starry Night\n副标题：星夜下的无词歌\n作曲：Polymath9 feat. LousikAEy\n编曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_0_story_intense_argue",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_intense_argue",
		musicName = "ATTENTION",
		id = 226,
		awbName = "bgm_activity_3_0_story_intense_argue",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_0_story_special_death",
		authorName = "Polymath9/LousikAEy",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_special_death",
		musicName = "White Annihilation",
		id = 227,
		awbName = "bgm_activity_3_0_story_special_death",
		initAISAC = "",
		detail = "生命因坚强而脆弱，又因脆弱而坚强。\n\n作曲：Polymath9\n编曲：Polymath9/LousikAEy"
	},
	{
		cueName = "bgm_activity_3_0_story_ominous",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_ominous",
		musicName = "Retrograde Raindrop",
		id = 228,
		awbName = "bgm_activity_3_0_story_ominous",
		initAISAC = "",
		detail = "在规则与界限当中，一切终将回到它原本的状态。存在归于存在，虚无归于虚无。\n\n作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_0_story_theme_orgel",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_theme_orgel",
		musicName = "My Precious Friend (Orgel Ver.)",
		id = 229,
		awbName = "bgm_activity_3_0_story_theme_orgel",
		initAISAC = "",
		detail = "「……想一想，将来还能去做很多开心的事，遇到很多爱你的人和你爱的人。」\n「所有美好的事物都会在未来等你，等你用笑容去珍惜它们。带上我的期盼一起——」\n「请好好生活下去。」\n\n曲名：My Precious Friend (Orgel Ver.)\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_0_story_theme_piano",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_theme_piano",
		musicName = "Your Fragile Future",
		id = 230,
		awbName = "bgm_activity_3_0_story_theme_piano",
		initAISAC = "",
		detail = "作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_0_story_theme_piano_orc",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_theme_piano_orc",
		musicName = "Our Little World",
		id = 231,
		awbName = "bgm_activity_3_0_story_theme_piano_orc",
		initAISAC = "",
		detail = "作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_0_dorm_idol_1",
		authorName = "LousikAEy/Polymath9",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_dorm_idol_1",
		musicName = "Rocking Spotlight",
		id = 232,
		awbName = "bgm_activity_3_0_dorm_idol_1",
		initAISAC = "",
		detail = "作曲：Polymath9\n编曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_0_story_return_song",
		authorName = "「深空之眼」修正者",
		ableBGM = 1,
		album = 17,
		cuesheet = "bgm_activity_3_0_story_return_song",
		musicName = "Sing For You",
		id = 233,
		awbName = "bgm_activity_3_0_story_return_song",
		initAISAC = "",
		detail = "欢迎回来，管理员。\n\n作曲：LousikAEy\nCV列表：\n薇儿丹蒂 – 牛奶君\n奥西里斯 – 皛四白\n利维坦 – 刘雯\n维达尔 – 蟲蟲\n前鬼坊天狗 – 韩娇娇"
	},
	{
		cueName = "bgm_activity_3_2_ui",
		authorName = "Polymath9/LousikAEy",
		ableBGM = 1,
		album = 18,
		cuesheet = "bgm_activity_3_2_ui",
		musicName = "Read A Dream",
		id = 234,
		awbName = "bgm_activity_3_2_ui",
		initAISAC = "",
		detail = "轻飘飘，亮晶晶，遥远模糊又破碎的梦境。\n\n作曲：Polymath9\n编曲：LousikAEy/Polymath9"
	},
	{
		cueName = "bgm_activity_3_2_battle_corridor_dream",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 18,
		cuesheet = "bgm_activity_3_2_battle_corridor_dream",
		musicName = "Painted March",
		id = 235,
		awbName = "bgm_activity_3_2_battle_corridor_dream",
		initAISAC = "",
		detail = "作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_2_story_corridor_dream",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 18,
		cuesheet = "bgm_activity_3_2_story_corridor_dream",
		musicName = "Pillow·Window·Rainbow",
		id = 236,
		awbName = "bgm_activity_3_2_story_corridor_dream",
		initAISAC = "",
		detail = "孩子把所有想象画在纸上，那是他们眼里世界的模样。\n\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_2_story_corridor_slow",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 18,
		cuesheet = "bgm_activity_3_2_story_corridor_slow",
		musicName = "Melting Candy",
		id = 237,
		awbName = "bgm_activity_3_2_story_corridor_slow",
		initAISAC = "",
		detail = "请走上蛋糕的台阶，推开饼干的房门，品尝糖果溶进的梦。\n\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_2_story_house_nightmare",
		authorName = "Polymath9/LousikAEy",
		ableBGM = 1,
		album = 18,
		cuesheet = "bgm_activity_3_2_story_house_nightmare",
		musicName = "Bitter Candy",
		id = 238,
		awbName = "bgm_activity_3_2_story_house_nightmare",
		initAISAC = "",
		detail = "她又一次回到自己家中，可糖果已经不再甜了。\n\n作曲：Polymath9\n编曲：LousikAEy/Polymath9"
	},
	{
		cueName = "bgm_minigame_2",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 18,
		cuesheet = "bgm_minigame_2",
		musicName = "Recess Time",
		id = 239,
		awbName = "bgm_minigame_2",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_3_2024summer_ui",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 19,
		cuesheet = "bgm_activity_3_3_2024summer_ui",
		musicName = "Summer Revelry",
		id = 240,
		awbName = "bgm_activity_3_3_2024summer_ui",
		initAISAC = "",
		detail = "阳光！海滩！音乐！在盛夏的舞动中，让所有的烦恼与忧愁都随汗水被甩脱吧！\n\n作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_3_3_2024summer_game",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 19,
		cuesheet = "bgm_activity_3_3_2024summer_game",
		musicName = "Delighted Joy",
		id = 241,
		awbName = "bgm_activity_3_3_2024summer_game",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_3_3_minigame_warchess",
		authorName = "CoyDe",
		ableBGM = 1,
		album = 19,
		cuesheet = "bgm_activity_3_3_minigame_warchess",
		musicName = "Vibrant Journey",
		id = 242,
		awbName = "bgm_activity_3_3_minigame_warchess",
		initAISAC = "",
		detail = "作曲：CoyDe"
	},
	{
		cueName = "bgm_activity_3_3_minigame_warchess_stage",
		authorName = "RabbitJ + Haloweak",
		ableBGM = 1,
		album = 19,
		cuesheet = "bgm_activity_3_3_minigame_warchess_stage",
		musicName = "Festive Beat",
		id = 243,
		awbName = "bgm_activity_3_3_minigame_warchess_stage",
		detail = "灯光就位，观众入席，盛大的舞台已经就位！举起双手，挥舞灯牌，迎接夏日最后的狂欢吧！\n\n作曲：RabbitJ + Haloweak",
		initAISAC = {
			{
				"phase_controller",
				0.5
			}
		}
	},
	{
		cueName = "bgm_activity_3_3_promotional_2024summer",
		authorName = "一口井",
		ableBGM = 1,
		album = 19,
		cuesheet = "bgm_activity_3_3_promotional_2024summer",
		musicName = "Bubble Word",
		id = 244,
		awbName = "bgm_activity_3_3_promotional_2024summer",
		initAISAC = "",
		detail = "回应着守护安宁的请求，少女的歌声飘扬在海边，休止台下的纷争。\n而与少女的羞涩一同藏于心底的，还有独属一人的旋律。\n\n演唱：一口井\n作曲：Polyblue\n作词：大九_LN\n贝斯：立崎レイン\n其他乐器：Polyblue"
	},
	{
		cueName = "bgm_minigame_3",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 19,
		cuesheet = "bgm_minigame_3",
		musicName = "Flurry Tap",
		id = 245,
		awbName = "bgm_minigame_3",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_4_ui",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 20,
		cuesheet = "bgm_activity_3_4_ui",
		musicName = "Chords Before Aurora",
		id = 246,
		awbName = "bgm_activity_3_4_ui",
		initAISAC = "",
		detail = "孤舟飘起长歌，破开墨色尽染的渊海。\n剑光照亮极夜，呼唤遥远的晨曦。\n\n作曲：Polymath9\n混音：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_4_battle_crete",
		authorName = "Polymath9/LousikAEy",
		ableBGM = 1,
		album = 20,
		cuesheet = "bgm_activity_3_4_battle_crete",
		musicName = "Harbinger of Torment",
		id = 247,
		awbName = "bgm_activity_3_4_battle_crete",
		initAISAC = "",
		detail = "作曲：Polymath9\n编曲：Polymath9/LousikAEy"
	},
	{
		cueName = "bgm_activity_3_4_battle_deck",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 20,
		cuesheet = "bgm_activity_3_4_battle_deck",
		musicName = "Tide of Calamity",
		id = 248,
		awbName = "bgm_activity_3_4_battle_deck",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_4_battle_seabed",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 20,
		cuesheet = "bgm_activity_3_4_battle_seabed",
		musicName = "Transcend the Abyss",
		id = 249,
		awbName = "bgm_activity_3_4_battle_seabed",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_4_battle_boss_4042_1",
		authorName = "Nevia",
		ableBGM = 1,
		album = 20,
		cuesheet = "bgm_activity_3_4_battle_boss_4042_1",
		musicName = "Maiden of Brume",
		id = 250,
		awbName = "bgm_activity_3_4_battle_boss_4042_1",
		initAISAC = "",
		detail = "怨恨与伤痛彼此纠缠，化为不应存在的亡灵。\n它自深渊归来，它向生者宣战。\n\n曲名：Maiden of Brume\n副标题：大雾深处的少女\n作曲：Nevia"
	},
	{
		cueName = "bgm_activity_3_4_battle_boss_4042_2",
		authorName = "VeetaCrush/S9ryne",
		ableBGM = 1,
		album = 20,
		cuesheet = "bgm_activity_3_4_battle_boss_4042_2",
		musicName = "Knell of Banshee",
		id = 251,
		awbName = "bgm_activity_3_4_battle_boss_4042_2",
		initAISAC = "",
		detail = "曲名：Knell of Banshee\n副标题：女妖的丧钟\n作曲：VeetaCrush/S9ryne"
	},
	{
		cueName = "bgm_activity_3_4_story_crete",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 20,
		cuesheet = "bgm_activity_3_4_story_crete",
		musicName = "Prelude of Gloaming",
		id = 252,
		awbName = "bgm_activity_3_4_story_crete",
		initAISAC = "",
		detail = "作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_4_story_deckbridge",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 20,
		cuesheet = "bgm_activity_3_4_story_deckbridge",
		musicName = "Swaying in the Mist",
		id = 253,
		awbName = "bgm_activity_3_4_story_deckbridge",
		initAISAC = "",
		detail = "大海不会遗忘，它铭记着破碎的梦，洒落的泪，以及一切苦涩的回忆。\n\n曲名：Swaying in the Mist\n副标题：雾中摇曳\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_4_story_crete_intense",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 20,
		cuesheet = "bgm_activity_3_4_story_crete_intense",
		musicName = "The Shadow Menace",
		id = 254,
		awbName = "bgm_activity_3_4_story_crete_intense",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_4_story_seabed_short",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 20,
		cuesheet = "bgm_activity_3_4_story_seabed_short",
		musicName = "Aqua End",
		id = 255,
		awbName = "bgm_activity_3_4_story_seabed_short",
		initAISAC = "",
		detail = "浸没，沉沦，迷失。深渊已经揭开面纱，欢迎迷途的游魂。\n\n作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_4_story_seabed",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 20,
		cuesheet = "bgm_activity_3_4_story_seabed",
		musicName = "Deeper than Deeper",
		id = 256,
		awbName = "bgm_activity_3_4_story_seabed",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_6_ui",
		authorName = "VeetaCrush",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_activity_3_6_ui",
		musicName = "Sarvaloka",
		id = 257,
		awbName = "bgm_activity_3_6_ui",
		initAISAC = "",
		detail = "过往，现在，未来，一切都将于此交汇。\n\n曲名：Sarvaloka\n副标题：森罗万象\n作曲：VeetaCrush/Polymath9\n编曲：VeetaCrush"
	},
	{
		cueName = "bgm_activity_3_6_battle_new_industry",
		authorName = "HJLL",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_activity_3_6_battle_new_industry",
		musicName = "Immotus",
		id = 258,
		awbName = "bgm_activity_3_6_battle_new_industry",
		initAISAC = "",
		detail = "作曲：HJLL"
	},
	{
		cueName = "bgm_activity_3_6_battle_rich_area",
		authorName = "HJLL",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_activity_3_6_battle_rich_area",
		musicName = "Stray into Shrine",
		id = 259,
		awbName = "bgm_activity_3_6_battle_rich_area",
		initAISAC = "",
		detail = "作曲：HJLL"
	},
	{
		cueName = "bgm_activity_3_6_story_new_industry",
		authorName = "LousikAEy/Polymath9/Mudsi",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_activity_3_6_story_new_industry",
		musicName = "Irresistible Change",
		id = 260,
		awbName = "bgm_activity_3_6_story_new_industry",
		initAISAC = "",
		detail = "作曲：Polymath9/Mudsi\n编曲：LousikAEy/Mudsi"
	},
	{
		cueName = "bgm_activity_3_6_story_rich_area",
		authorName = "Polymath9/LousikAEy",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_activity_3_6_story_rich_area",
		musicName = "Ab Aeterno",
		id = 261,
		awbName = "bgm_activity_3_6_story_rich_area",
		initAISAC = "",
		detail = "作曲：Polymath9\n编曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_6_story_brahma_enter",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_activity_3_6_story_brahma_enter",
		musicName = "Inviolability",
		id = 262,
		awbName = "bgm_activity_3_6_story_brahma_enter",
		initAISAC = "",
		detail = "她是始，她是终，她是此间的一切。\n除此之外，再无他物。\n\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_6_story_shashvat_quiet",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_activity_3_6_story_shashvat_quiet",
		musicName = "Kaalasya Nadii",
		id = 263,
		awbName = "bgm_activity_3_6_story_shashvat_quiet",
		initAISAC = "",
		detail = "时光悄然流淌，留下名为记忆的沉积。\n\n曲名：Kaalasya Nadii\n副标题：时间的河流\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_6_rogue_xuheng_title",
		authorName = "melo",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_activity_3_6_rogue_xuheng_title",
		musicName = "绕重山",
		id = 264,
		awbName = "bgm_activity_3_6_rogue_xuheng_title",
		initAISAC = "",
		detail = "百转千回，踏过峰峦叠嶂。蓦然回首，坐看过眼云烟。\n\n作曲：melo"
	},
	{
		cueName = "bgm_activity_3_6_rogue_xuheng_rest",
		authorName = "melo",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_activity_3_6_rogue_xuheng_rest",
		musicName = "卧云烟",
		id = 265,
		awbName = "bgm_activity_3_6_rogue_xuheng_rest",
		initAISAC = "",
		detail = "作曲：melo"
	},
	{
		cueName = "bgm_activity_3_6_rogue_xuheng_NE",
		authorName = "melo",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_activity_3_6_rogue_xuheng_NE",
		musicName = "行路远",
		id = 266,
		awbName = "bgm_activity_3_6_rogue_xuheng_NE",
		initAISAC = "",
		detail = "作曲：melo"
	},
	{
		cueName = "bgm_minigame_4",
		authorName = "Feather7",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_minigame_4",
		musicName = "Happiness in Hand",
		id = 267,
		awbName = "bgm_minigame_4",
		initAISAC = "",
		detail = "作曲：Feather7\n混音：Mudsi"
	},
	{
		cueName = "bgm_side_daily08",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_side_daily08",
		musicName = "Mild in Mind",
		id = 268,
		awbName = "bgm_side_daily08",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_6_battle_biotech",
		authorName = "HJLL",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_activity_3_6_battle_biotech",
		musicName = "Dominant Mutation",
		id = 269,
		awbName = "bgm_activity_3_6_battle_biotech",
		initAISAC = "",
		detail = "作曲：HJLL"
	},
	{
		cueName = "bgm_activity_3_6_story_biotech",
		authorName = "Polymath9/LousikAEy",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_activity_3_6_story_biotech",
		musicName = "Molecular Evolution",
		id = 270,
		awbName = "bgm_activity_3_6_story_biotech",
		initAISAC = "",
		detail = "作曲：Polymath9/LousikAEy\n编曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_6_story_brahma_restore",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_activity_3_6_story_brahma_restore",
		musicName = "Reversibility",
		id = 271,
		awbName = "bgm_activity_3_6_story_brahma_restore",
		initAISAC = "",
		detail = "一念成幻，一念成真。\n\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_6_battle_boss_4043",
		authorName = "HJLL",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_activity_3_6_battle_boss_4043",
		musicName = "Daitya Karan",
		id = 272,
		awbName = "bgm_activity_3_6_battle_boss_4043",
		initAISAC = "",
		detail = "当你忘记痛苦，也就忘记了为何而活。\n\n作曲：HJLL"
	},
	{
		cueName = "bgm_activity_3_7_story_109502_star",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_activity_3_7_story_109502_star",
		musicName = "Murmurs of Nebulae",
		id = 273,
		awbName = "bgm_activity_3_7_story_109502_star",
		initAISAC = "",
		detail = "想念夜风亲吻与你并排的草地，想念星星很远但你很近，想念你悄悄对我说过的话，想念有你也有我们的未来。\n\n曲名：Murmurs of Nebulae\n副标题：星云的低语\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_7_scene_109502_day",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_activity_3_7_scene_109502_day",
		musicName = "Morningtime Stories",
		id = 274,
		awbName = "bgm_activity_3_7_scene_109502_day",
		initAISAC = "",
		detail = "习惯了起床时的问候，如过去的每一天。\n\n曲名：Morningtime Stories\n副标题：晨间故事\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_7_scene_109502_night",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 21,
		cuesheet = "bgm_activity_3_7_scene_109502_night",
		musicName = "Look, the rain...outside.",
		id = 275,
		awbName = "bgm_activity_3_7_scene_109502_night",
		initAISAC = "",
		detail = "习惯了入睡前的道别，如过去的每一天。\n\n曲名：Look, the rain...outside.\n副标题：看……下雨了，外面。\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_8_ui",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 22,
		cuesheet = "bgm_activity_3_8_ui",
		musicName = "Mists Maze",
		id = 276,
		awbName = "bgm_activity_3_8_ui",
		initAISAC = "",
		detail = "潮水翻涌，雾中出路难寻。\n失陷深海，虹色筑桥破局。\n\n曲名：Mists Maze\n副标题：雾魇迷途\n作曲：Polymath9\n混音：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_8_battle_northwake",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 22,
		cuesheet = "bgm_activity_3_8_battle_northwake",
		musicName = "Warning Line",
		id = 277,
		awbName = "bgm_activity_3_8_battle_northwake",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_8_battle_tide",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 22,
		cuesheet = "bgm_activity_3_8_battle_tide",
		musicName = "Restless Tide",
		id = 278,
		awbName = "bgm_activity_3_8_battle_tide",
		initAISAC = "",
		detail = "作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_8_story_northwake_1",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 22,
		cuesheet = "bgm_activity_3_8_story_northwake_1",
		musicName = "Diffusing Mists",
		id = 279,
		awbName = "bgm_activity_3_8_story_northwake_1",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_8_story_northwake_2",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 22,
		cuesheet = "bgm_activity_3_8_story_northwake_2",
		musicName = "The Coast without Lights",
		id = 280,
		awbName = "bgm_activity_3_8_story_northwake_2",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_8_story_village",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 22,
		cuesheet = "bgm_activity_3_8_story_village",
		musicName = "Shore Memories",
		id = 281,
		awbName = "bgm_activity_3_8_story_village",
		initAISAC = "",
		detail = "这里似乎从未改变，如同吹拂在脸颊上的风带着的熟悉咸气。\n\n曲名：Shore Memories\n副标题：盐风回忆\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_8_story_corg",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 22,
		cuesheet = "bgm_activity_3_8_story_corg",
		musicName = "Line of Defense",
		id = 282,
		awbName = "bgm_activity_3_8_story_corg",
		initAISAC = "",
		detail = "它守护着危险与安全的边界线。\n\n作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_8_story_tide",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 22,
		cuesheet = "bgm_activity_3_8_story_tide",
		musicName = "Shadows Behind",
		id = 283,
		awbName = "bgm_activity_3_8_story_tide",
		initAISAC = "",
		detail = "雾中暗影隐匿着自己的身形……小心，它们已经盯上了你。\n\n曲名：Shadows Behind\n副标题：身后影\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_8_story_tide_battle",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 22,
		cuesheet = "bgm_activity_3_8_story_tide_battle",
		musicName = "A Swindle",
		id = 284,
		awbName = "bgm_activity_3_8_story_tide_battle",
		initAISAC = "",
		detail = "作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_9_battle_boss_4044_1",
		authorName = "HJLL",
		ableBGM = 1,
		album = 22,
		cuesheet = "bgm_activity_3_9_battle_boss_4044_1",
		musicName = "Curtain Unveiled",
		id = 285,
		awbName = "bgm_activity_3_9_battle_boss_4044_1",
		initAISAC = "",
		detail = "帷幕悄然拉开，演员也已就位。\n这盛大的死亡剧目，没有人可以逃脱。\n\n作曲：HJLL"
	},
	{
		cueName = "bgm_activity_3_9_battle_boss_4044_2",
		authorName = "HJLL",
		ableBGM = 1,
		album = 22,
		cuesheet = "bgm_activity_3_9_battle_boss_4044_2",
		musicName = "Fatal Trick",
		id = 286,
		awbName = "bgm_activity_3_9_battle_boss_4044_2",
		initAISAC = "",
		detail = "作曲：HJLL"
	},
	{
		cueName = "bgm_activity_3_9_minigame_ball",
		authorName = "Feather7",
		ableBGM = 1,
		album = 22,
		cuesheet = "bgm_activity_3_9_minigame_ball",
		musicName = "Wander in the Deep Wild",
		id = 287,
		awbName = "bgm_activity_3_9_minigame_ball",
		initAISAC = "",
		detail = "作曲：Feather7\n混音：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_10_ui",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 23,
		cuesheet = "bgm_activity_3_10_ui",
		musicName = "Riffle",
		id = 288,
		awbName = "bgm_activity_3_10_ui",
		initAISAC = "",
		detail = "面对战争，我们只能有一种声音。\n\n作曲：Polymath9\n编曲：Polymath9/Mudsi\n混音：Mudsi"
	},
	{
		cueName = "bgm_activity_3_10_ui_clean",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 23,
		cuesheet = "bgm_activity_3_10_ui_clean",
		musicName = "Riffle -Pure Version-",
		id = 289,
		awbName = "bgm_activity_3_10_ui_clean",
		initAISAC = "",
		detail = "作曲：Polymath9\n编曲：Polymath9/Mudsi\n混音：Mudsi"
	},
	{
		cueName = "bgm_activity_3_10_battle",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 23,
		cuesheet = "bgm_activity_3_10_battle",
		musicName = "Unjust Bullet",
		id = 290,
		awbName = "bgm_activity_3_10_battle",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_10_story_yard",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 23,
		cuesheet = "bgm_activity_3_10_story_yard",
		musicName = "Through the Gloaming",
		id = 291,
		awbName = "bgm_activity_3_10_story_yard",
		initAISAC = "",
		detail = "小院就在那儿，一直都在那儿。\n\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_10_story_daily_acoustic",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 23,
		cuesheet = "bgm_activity_3_10_story_daily_acoustic",
		musicName = "That's the Way We Survive",
		id = 292,
		awbName = "bgm_activity_3_10_story_daily_acoustic",
		initAISAC = "",
		detail = "曲名：That's the Way We Survive\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_10_story_daily",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 23,
		cuesheet = "bgm_activity_3_10_story_daily",
		musicName = "Keep the Shadow Breathing",
		id = 293,
		awbName = "bgm_activity_3_10_story_daily",
		initAISAC = "",
		detail = "曲名：Keep the Shadow Breathing\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_10_story_corg_base",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 23,
		cuesheet = "bgm_activity_3_10_story_corg_base",
		musicName = "Walled Garden",
		id = 294,
		awbName = "bgm_activity_3_10_story_corg_base",
		initAISAC = "",
		detail = "作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_10_story_scheme_1",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 23,
		cuesheet = "bgm_activity_3_10_story_scheme_1",
		musicName = "Final Agenda",
		id = 295,
		awbName = "bgm_activity_3_10_story_scheme_1",
		initAISAC = "",
		detail = "能在科尔盖坐到高位的人，谁的信念会动摇呢？\n\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_10_story_scheme_2",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 23,
		cuesheet = "bgm_activity_3_10_story_scheme_2",
		musicName = "Recesses of Secrets",
		id = 296,
		awbName = "bgm_activity_3_10_story_scheme_2",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_10_story_mountain",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 23,
		cuesheet = "bgm_activity_3_10_story_mountain",
		musicName = "Silverpine",
		id = 297,
		awbName = "bgm_activity_3_10_story_mountain",
		initAISAC = "",
		detail = "作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_10_story_prison",
		authorName = "Polymath9",
		ableBGM = 1,
		album = 23,
		cuesheet = "bgm_activity_3_10_story_prison",
		musicName = "Answer the Choice",
		id = 298,
		awbName = "bgm_activity_3_10_story_prison",
		initAISAC = "",
		detail = "谁才是那个罪犯？\n\n作曲：Polymath9"
	},
	{
		cueName = "bgm_activity_3_10_story_dock",
		authorName = "Polymath9/LousikAEy",
		ableBGM = 1,
		album = 23,
		cuesheet = "bgm_activity_3_10_story_dock",
		musicName = "Divergency",
		id = 299,
		awbName = "bgm_activity_3_10_story_dock",
		initAISAC = "",
		detail = "忘记你不该知道的事情。\n\n作曲：Polymath9\n编曲：LousikAEy/Mudsi"
	},
	{
		cueName = "bgm_side_daily10",
		authorName = "Feather7",
		ableBGM = 1,
		album = 23,
		cuesheet = "bgm_side_daily10",
		musicName = "Our Diaries",
		id = 300,
		awbName = "bgm_side_daily10",
		initAISAC = "",
		detail = "作曲：Feather7"
	},
	{
		cueName = "bgm_activity_3_10_spring_day_1",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 23,
		cuesheet = "bgm_activity_3_10_spring_day_1",
		musicName = "画中客",
		id = 301,
		awbName = "bgm_activity_3_10_spring_day_1",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_10_spring_day_2",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 23,
		cuesheet = "bgm_activity_3_10_spring_day_2",
		musicName = "不知处",
		id = 302,
		awbName = "bgm_activity_3_10_spring_day_2",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	{
		cueName = "bgm_activity_3_10_spring_night",
		authorName = "LousikAEy",
		ableBGM = 1,
		album = 23,
		cuesheet = "bgm_activity_3_10_spring_night",
		musicName = "天街游",
		id = 303,
		awbName = "bgm_activity_3_10_spring_night",
		initAISAC = "",
		detail = "作曲：LousikAEy"
	},
	get_id_list_by_album = {
		[23] = {
			288,
			289,
			290,
			291,
			292,
			293,
			294,
			295,
			296,
			297,
			298,
			299,
			300,
			301,
			302,
			303
		},
		[22] = {
			276,
			277,
			278,
			279,
			280,
			281,
			282,
			283,
			284,
			285,
			286,
			287
		},
		[21] = {
			257,
			258,
			259,
			260,
			261,
			262,
			263,
			264,
			265,
			266,
			267,
			268,
			269,
			270,
			271,
			272,
			273,
			274,
			275
		},
		[20] = {
			246,
			247,
			248,
			249,
			250,
			251,
			252,
			253,
			254,
			255,
			256
		},
		[19] = {
			240,
			241,
			242,
			243,
			244,
			245
		},
		[18] = {
			234,
			235,
			236,
			237,
			238,
			239
		},
		[17] = {
			203,
			204,
			205,
			206,
			207,
			208,
			209,
			210,
			211,
			212,
			213,
			214,
			215,
			216,
			217,
			218,
			219,
			220,
			221,
			222,
			223,
			224,
			225,
			226,
			227,
			228,
			229,
			230,
			231,
			232,
			233
		},
		[16] = {
			187,
			188,
			189,
			190,
			191,
			192,
			193,
			194,
			195,
			196,
			197,
			198,
			199,
			200
		},
		[15] = {
			175,
			176,
			177,
			178,
			179,
			180,
			181,
			182,
			183,
			184,
			185,
			186
		},
		[14] = {
			161,
			162,
			163,
			164,
			165,
			166,
			167,
			168,
			169,
			170,
			171,
			172,
			173,
			174
		},
		[13] = {
			152,
			153,
			154,
			155,
			156,
			157,
			158,
			159,
			160
		},
		[12] = {
			133,
			134,
			135,
			136,
			137,
			138,
			139,
			140,
			141,
			142,
			143,
			144,
			145,
			146,
			147,
			148,
			149,
			150,
			151
		},
		[11] = {
			120,
			121,
			122,
			123,
			124,
			125,
			126,
			127,
			128,
			129,
			130,
			131,
			132
		},
		[10] = {
			107,
			108,
			109,
			110,
			111,
			112,
			113,
			114,
			115,
			116,
			117,
			118,
			119
		},
		[9] = {
			104,
			105,
			106
		},
		[8] = {
			88,
			89,
			90,
			91,
			92,
			93,
			94,
			95,
			96,
			97,
			98,
			99,
			100,
			101,
			102,
			103
		},
		[7] = {
			81,
			82,
			83,
			84,
			85,
			86,
			87
		},
		[6] = {
			68,
			69,
			70,
			71,
			72,
			73,
			74,
			75,
			76,
			77,
			78,
			79,
			80
		},
		[5] = {
			58,
			59,
			60,
			61,
			62,
			63,
			64,
			65,
			66,
			67
		},
		[4] = {
			42,
			43,
			44,
			45,
			46,
			47,
			48,
			49,
			50,
			51,
			52,
			53,
			54,
			55,
			56,
			57
		},
		[3] = {
			32,
			33,
			34,
			35,
			36,
			37,
			38,
			39,
			40,
			41
		},
		[2] = {
			31
		},
		{
			1,
			2,
			3,
			4,
			5,
			6,
			7,
			8,
			9,
			10,
			11,
			12,
			13,
			14,
			15,
			16,
			17,
			18,
			19,
			20,
			21,
			22,
			23,
			24,
			25,
			26,
			27,
			28,
			29,
			30,
			201,
			202
		}
	},
	all = {
		1,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9,
		10,
		11,
		12,
		13,
		14,
		15,
		16,
		17,
		18,
		19,
		20,
		21,
		22,
		23,
		24,
		25,
		26,
		27,
		28,
		29,
		30,
		31,
		32,
		33,
		34,
		35,
		36,
		37,
		38,
		39,
		40,
		41,
		42,
		43,
		44,
		45,
		46,
		47,
		48,
		49,
		50,
		51,
		52,
		53,
		54,
		55,
		56,
		57,
		58,
		59,
		60,
		61,
		62,
		63,
		64,
		65,
		66,
		67,
		68,
		69,
		70,
		71,
		72,
		73,
		74,
		75,
		76,
		77,
		78,
		79,
		80,
		81,
		82,
		83,
		84,
		85,
		86,
		87,
		88,
		89,
		90,
		91,
		92,
		93,
		94,
		95,
		96,
		97,
		98,
		99,
		100,
		101,
		102,
		103,
		104,
		105,
		106,
		107,
		108,
		109,
		110,
		111,
		112,
		113,
		114,
		115,
		116,
		117,
		118,
		119,
		120,
		121,
		122,
		123,
		124,
		125,
		126,
		127,
		128,
		129,
		130,
		131,
		132,
		133,
		134,
		135,
		136,
		137,
		138,
		139,
		140,
		141,
		142,
		143,
		144,
		145,
		146,
		147,
		148,
		149,
		150,
		151,
		152,
		153,
		154,
		155,
		156,
		157,
		158,
		159,
		160,
		161,
		162,
		163,
		164,
		165,
		166,
		167,
		168,
		169,
		170,
		171,
		172,
		173,
		174,
		175,
		176,
		177,
		178,
		179,
		180,
		181,
		182,
		183,
		184,
		185,
		186,
		187,
		188,
		189,
		190,
		191,
		192,
		193,
		194,
		195,
		196,
		197,
		198,
		199,
		200,
		201,
		202,
		203,
		204,
		205,
		206,
		207,
		208,
		209,
		210,
		211,
		212,
		213,
		214,
		215,
		216,
		217,
		218,
		219,
		220,
		221,
		222,
		223,
		224,
		225,
		226,
		227,
		228,
		229,
		230,
		231,
		232,
		233,
		234,
		235,
		236,
		237,
		238,
		239,
		240,
		241,
		242,
		243,
		244,
		245,
		246,
		247,
		248,
		249,
		250,
		251,
		252,
		253,
		254,
		255,
		256,
		257,
		258,
		259,
		260,
		261,
		262,
		263,
		264,
		265,
		266,
		267,
		268,
		269,
		270,
		271,
		272,
		273,
		274,
		275,
		276,
		277,
		278,
		279,
		280,
		281,
		282,
		283,
		284,
		285,
		286,
		287,
		288,
		289,
		290,
		291,
		292,
		293,
		294,
		295,
		296,
		297,
		298,
		299,
		300,
		301,
		302,
		303
	}
}
